/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-10-27 00:31:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.stu.aca;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dualMajorMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1662347357502L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ================================================= -->\r\n");
      out.write("<!-- MAIN-CONTENT -->\r\n");
      out.write("<!-- ================================================= -->\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("		<div class=\"card-body\">\r\n");
      out.write("<div class=\"main-content-jsp\">\r\n");
      out.write("    \r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- 본문 1 -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("        <div class=\"col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<h3 class=\"card-header\"><i class=\"fas fa-clipboard\"></i>&nbsp;&nbsp;부/복수전공 신청 공지 조회</h3>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li>부/복수전공 가능한 학과(부)전공 정보를 조회할 수 있는 화면입니다.</li>\r\n");
      out.write("						<li>학과 홈페이지를 클릭하면 해당 학과(부)전공의 페이지로 이동합니다.</li>\r\n");
      out.write("						<li>신청 버튼을 클릭하면 부/복수전공 신청할 수 있는 화면으로 이동합니다.</li>\r\n");
      out.write("			        </ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div> \r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("        <div class=\"col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<h3 class=\"card-header\"><i class=\"fas fa-clipboard\"></i>&nbsp;&nbsp;유의사항</h3>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li>부전공은 1개, 복수전공은 2개까지 신청이 가능합니다.</li>\r\n");
      out.write("			        </ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div> \r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("	<div class=\"col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("		<div class=\"card\">\r\n");
      out.write("			<div class=\"card-body\">\r\n");
      out.write("	\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-3 mb-3\">\r\n");
      out.write("						<label for=\"country\">분과대학</label>\r\n");
      out.write("						<select id=\"collegeSelect\" name=\"collegeCd\" class=\"custom-select d-block w-100\" onchange=\"getMajorListByCollegeCd()\" id=\"country\" required=\"\">\r\n");
      out.write("							<option value=\"\">선택</option>\r\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						</select>\r\n");
      out.write("					<div class=\"invalid-feedback\">\r\n");
      out.write("						분과대학을 선택하세요\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-4 mb-3\">\r\n");
      out.write("						<label for=\"state\">학과(부)</label>\r\n");
      out.write("						<select id=\"majorSelect\" name=\"majorCd\" class=\"custom-select d-block w-100\" id=\"state\" required=\"\">\r\n");
      out.write("							<option value=\"\">선택</option>\r\n");
      out.write("							<option>아시아언어문명학부</option>\r\n");
      out.write("						</select>\r\n");
      out.write("						<div class=\"invalid-feedback\">\r\n");
      out.write("							학과(부)를 선택하세요\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-4 mb-3\">\r\n");
      out.write("						<label for=\"state\">전공</label>\r\n");
      out.write("						<select class=\"custom-select d-block w-100\" id=\"state\" required=\"\">\r\n");
      out.write("							<option value=\"\">선택</option>\r\n");
      out.write("							<option>인도언어문명전공</option>\r\n");
      out.write("						</select>\r\n");
      out.write("						<div class=\"invalid-feedback\">\r\n");
      out.write("							전공을 선택하세요\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-1 mb-3\">\r\n");
      out.write("						<label for=\"state\"></label>\r\n");
      out.write("						<span class=\"input-group-append\">\r\n");
      out.write("	      					<button class=\"btn btn-primary\" type=\"button\" \r\n");
      out.write("	            					id=\"searchBtn\" onclick=\"list_go(1);\">검색</button>\r\n");
      out.write("	   					</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("	\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div> \r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- 본문 2 -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("        <div class=\"col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("	<div class=\"card\">\r\n");
      out.write("		<h4 class=\"card-header\">[검색결과]</h4>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"card-body\">\r\n");
      out.write("			<table class=\"table table-hover\">\r\n");
      out.write("			    <thead>\r\n");
      out.write("			        <tr>\r\n");
      out.write("			            <th>구분</th>\r\n");
      out.write("			            <th>분과대학</th>\r\n");
      out.write("			            <th>학과(부)</th>\r\n");
      out.write("			            <th>전공</th>\r\n");
      out.write("			            <th></th>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			    </thead>\r\n");
      out.write("			    <tbody>\r\n");
      out.write("			        <tr>\r\n");
      out.write("			        	<td style=\"width : 10%\">\r\n");
      out.write("			        		<select class=\"form-control\" id=\"input-select\">\r\n");
      out.write("								<option>선택</option>\r\n");
      out.write("								<option>제 2전공</option>\r\n");
      out.write("								<option>제 3전공</option>\r\n");
      out.write("								<option>부전공</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</td>\r\n");
      out.write("			            <td style=\"width : 10%\">인문대학</td>\r\n");
      out.write("			            <td style=\"width : 15%\">아시아언어문명학부</td>\r\n");
      out.write("			            <td style=\"width : 25%\">인도언어문명전공</td>\r\n");
      out.write("			            <td style=\"width : 20%\"><a href=\"#\" class=\"btn btn-primary btn-sm\">홈페이지</a>&nbsp;\r\n");
      out.write("			            &nbsp;<a href=\"#\" class=\"btn btn-primary btn-sm\" onclick=\"OpenWindow('");
      out.print(request.getContextPath());
      out.write("/stu/aca/dualMajor/applyPage','글쓰기',1280,650);\">부/복수전공신청</a></td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			    </tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("	</div> \r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- 본문2 끝 -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ================================================= -->\r\n");
      out.write("<!-- MAIN-CONTENT 끝 -->\r\n");
      out.write("<!-- ================================================= -->\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.7/handlebars.min.js\" ></script>\r\n");
      out.write("<script  type=\"text/x-handlebars-template\"  id=\"searchMajorListTemplate\">\r\n");
      out.write("	{{#each .}}\r\n");
      out.write("<tr>\r\n");
      out.write("     <td style=\"width : 20%\">{{colName}}</td>\r\n");
      out.write("     <td style=\"width : 25%\">{{majorName}}</td>\r\n");
      out.write("     <td style=\"width : 10%\">{{inPersonnel}}</td>\r\n");
      out.write("     <td style=\"width : 10%\">{{outPersonnel}}</td>\r\n");
      out.write("     <td style=\"width : 15%\"><a href=\"{{majorWeb}}\" class=\"btn btn-primary btn-sm\">홈페이지</a>&nbsp;&nbsp;\r\n");
      out.write("	<a href=\"#\" class=\"btn btn-primary btn-sm\" onclick=\"OpenWindow('");
      out.print(request.getContextPath());
      out.write("/stu/aca/changeMajor/applyPage?colName={{colName}}&majorName={{majorName}}','신청페이지',1280,650);\">전과신청</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("	{{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function printData(dataArr,target,templateObject){\r\n");
      out.write("	var template=Handlebars.compile(templateObject.html());\r\n");
      out.write("	var html = template(dataArr);	\r\n");
      out.write("	target.html(html);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getMajorListByCollegeCd(){\r\n");
      out.write("	var collegeCd = $(\"select[name=collegeCd\").val();\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url : \"");
      out.print(request.getContextPath());
      out.write("/stu/aca/majorList\",\r\n");
      out.write("		data : {\"collegeCd\":collegeCd},\r\n");
      out.write("		type:\"post\",\r\n");
      out.write("		dataType:\"json\",\r\n");
      out.write("		success:function(data){\r\n");
      out.write("			var majorSelect = document.getElementById(\"majorSelect\");\r\n");
      out.write("			var result = \"\";\r\n");
      out.write("			for(var i=0;i<data.length;i++){\r\n");
      out.write("				result+=\"<option value='none'>선택</option>\"\r\n");
      out.write("				result+=\"<option value=\"+data[i].majorCd+\">\"+data[i].majorName+\"</option>\";\r\n");
      out.write("			}\r\n");
      out.write("			majorSelect.innerHTML=result; \r\n");
      out.write("		},\r\n");
      out.write("		error:function(){\r\n");
      out.write("			alert(\"실패\");\r\n");
      out.write("		}\r\n");
      out.write("			\r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function searchMajorList(){\r\n");
      out.write("	var collegeCd = $(\"select[name=collegeCd\").val();\r\n");
      out.write("	var majorCd = $(\"select[name=majorCd]\").val();\r\n");
      out.write("	if(!collegeCd&&!majorCd){\r\n");
      out.write("		alert(\"검색할 항목을 선택해주세요.\");\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:\"");
      out.print(request.getContextPath());
      out.write("/stu/aca/searchMajorList\",\r\n");
      out.write("		data:{\r\n");
      out.write("			\"colCd\":collegeCd,\r\n");
      out.write("			\"majorCd\":majorCd	\r\n");
      out.write("		},\r\n");
      out.write("		type:\"post\",\r\n");
      out.write("		dataType:\"json\",\r\n");
      out.write("		success:function(data){\r\n");
      out.write("			printData(data,$('#searchMajorList'),$('#searchMajorListTemplate'))\r\n");
      out.write("		},\r\n");
      out.write("		error:function(){\r\n");
      out.write("			alert(\"실패\");\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/stu/aca/dualMajorMain.jsp(56,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/stu/aca/dualMajorMain.jsp(56,7) '${collegeList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${collegeList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/stu/aca/dualMajorMain.jsp(56,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("college");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("								<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${college.colCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${college.colName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
