/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-10-25 07:35:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.stu.aca;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class graduate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1662347357502L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("<div class=\"tab-outline\">\r\n");
      out.write("	<ul class=\"nav nav-tabs\" id=\"myTab2\" role=\"tablist\">\r\n");
      out.write("		<li class=\"nav-item\">\r\n");
      out.write("			<a class=\"nav-link active show\" id=\"tab-outline-one\" data-toggle=\"tab\" href=\"#outline-one\" role=\"tab\" aria-controls=\"home\" aria-selected=\"false\">졸업 신청</a>\r\n");
      out.write("		</li>\r\n");
      out.write("		<li class=\"nav-item\">\r\n");
      out.write("			<a class=\"nav-link\" id=\"tab-outline-two\" data-toggle=\"tab\" href=\"#outline-two\" role=\"tab\" aria-controls=\"profile\" aria-selected=\"true\">조기졸업/유예 신청</a>\r\n");
      out.write("		</li>\r\n");
      out.write("\r\n");
      out.write("	</ul>\r\n");
      out.write("	<div class=\"tab-content\" id=\"myTabContent2\">\r\n");
      out.write("		<div class=\"tab-pane fade\" id=\"outline-one\" role=\"tabpanel\" aria-labelledby=\"tab-outline-one\">\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("		<div class=\"card-body\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("             <div class=\"row\">\r\n");
      out.write("                 <div class=\"col-xl-2 col-lg-4 col-md-4 col-sm-4 col-12\">\r\n");
      out.write("                     <div class=\"text-center\">\r\n");
      out.write("<!--                          <img src=\"ddit/resources/img/jj.jpg\" alt=\"사용자이미지\" class=\"rounded-circle user-avatar-xxl\"> -->\r\n");
      out.write("                         <img src=\"ddit/resources/img/jj.jpg\" class=\"img-thumbnail mr-3\" alt=\"사용자이미지\">\r\n");
      out.write("                     </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("            	<div class=\"col-xl-10 col-lg-8 col-md-8 col-sm-8 col-12\">\r\n");
      out.write("                <div class=\"user-avatar-info\">\r\n");
      out.write("                    <!--  <div class=\"float-right\"><a href=\"#\" class=\"user-avatar-email text-secondary\">www.henrybarbara.com</a></div> -->\r\n");
      out.write("                    <div class=\"user-avatar-address\">\r\n");
      out.write("                        <div class=\"col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("								<div class=\"card\">\r\n");
      out.write("								<h3 class=\"card-header\"><i class=\"fas fa-user\"></i>&nbsp;&nbsp;학생기본정보</h3>\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("										<table class=\"table table-hover\">\r\n");
      out.write("										    <thead>\r\n");
      out.write("										        <tr>\r\n");
      out.write("										            <th style=\"width:10%\">학번</th>\r\n");
      out.write("										            <th style=\"width:10%\">이름</th>\r\n");
      out.write("										            <th style=\"width:15%\">학년</th>\r\n");
      out.write("										            <th style=\"width:15%\">분과대학</th>\r\n");
      out.write("										            <th style=\"width:15%\">학과</th>\r\n");
      out.write("										            <th style=\"width:25%\">입학일자</th>\r\n");
      out.write("										        </tr>\r\n");
      out.write("										    </thead>\r\n");
      out.write("										    <tbody>\r\n");
      out.write("										        <tr>\r\n");
      out.write("										            <td>학번</td>\r\n");
      out.write("										            <td>학년</td>\r\n");
      out.write("										            <td>학기</td>\r\n");
      out.write("										            <td>입학일</td>\r\n");
      out.write("										            <td>국적</td>\r\n");
      out.write("										            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("										        </tr>\r\n");
      out.write("										    </tbody>\r\n");
      out.write("										   \r\n");
      out.write("										    <thead>\r\n");
      out.write("										         <tr>\r\n");
      out.write("										            <th >전공</th>\r\n");
      out.write("										            <th >제2전공</th>\r\n");
      out.write("										            <th >제3전공</th>\r\n");
      out.write("										            <th >부전공</th>\r\n");
      out.write("										            <th >연락처</th>\r\n");
      out.write("										            <th >이메일</th>\r\n");
      out.write("										        </tr>\r\n");
      out.write("										    </thead>\r\n");
      out.write("										    <tbody>\r\n");
      out.write("										        <tr>\r\n");
      out.write("										            <td>전공</td>\r\n");
      out.write("										            <td>영문학</td>\r\n");
      out.write("										            <td>신청가능학점</td>\r\n");
      out.write("										            <td>2</td>\r\n");
      out.write("										            <td>011-2323-5444</td>\r\n");
      out.write("										            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("										        </tr>\r\n");
      out.write("										    </tbody>\r\n");
      out.write("										    <thead>\r\n");
      out.write("										         <tr>\r\n");
      out.write("										            <th >총이수학점</th>\r\n");
      out.write("										            <th >졸업이수학점</th>\r\n");
      out.write("										            <th >토익 자격증 여부</th>\r\n");
      out.write("										            <th >컴활 자격증 여부</th>\r\n");
      out.write("										            <th colspan=\"2\">주소</th>\r\n");
      out.write("										        </tr>\r\n");
      out.write("										    </thead>\r\n");
      out.write("										    <tbody>\r\n");
      out.write("										        <tr>\r\n");
      out.write("										            <td>학부</td>\r\n");
      out.write("										            <td>동아리</td>\r\n");
      out.write("										            <td>0</td>\r\n");
      out.write("										            <td>부전공</td>\r\n");
      out.write("										            <td colspan=\"2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.add1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.add2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("										        </tr>\r\n");
      out.write("										    </tbody>\r\n");
      out.write("										</table>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- 본문 1 -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("        <div class=\"col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<h3 class=\"card-header\"><i class=\"fas fa-clipboard\"></i>&nbsp;&nbsp;유의사항</h3>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li>조기 졸업의 경우 3학년 2학기 이후 신청이 가능합니다.</li>\r\n");
      out.write("						<li>학과별 졸업 요건이 다를 수 있으니 자세한 사항은 과 사무실을 통해 확인해주세요.</li>\r\n");
      out.write("			        </ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("        <div class=\"col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<h3 class=\"card-header\"><i class=\"fas fa-graduation-cap\"></i>&nbsp;&nbsp;졸업요건</h3>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li>졸업 신청을 위해선 아래의 자격증이 제출되어야 합니다.</li>\r\n");
      out.write("						<li>토익 자격증, 컴퓨터활용능력 자격중, 기타 자격증</li>\r\n");
      out.write("			        </ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- 본문1 끝 -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- 본문 2 -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("        <div class=\"col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("	<div class=\"card\">\r\n");
      out.write("		<h5 class=\"card-header\">제출내역</h5>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"card-body\">\r\n");
      out.write("			<table class=\"table table-hover\">\r\n");
      out.write("			    <thead>\r\n");
      out.write("			        <tr>\r\n");
      out.write("			            <th>제출자격증</th>\r\n");
      out.write("			            <th>제출날짜</th>\r\n");
      out.write("			            <th>확인여부</th>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			    </thead>\r\n");
      out.write("			    <tbody>\r\n");
      out.write("			        <tr>\r\n");
      out.write("			            <td style=\"width : 25%\">토익자격증</td>\r\n");
      out.write("			            <td style=\"width : 25%\">2022-07-06</td>\r\n");
      out.write("			            <td style=\"width : 25%\">대기</td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			        <tr>\r\n");
      out.write("			            <td style=\"width : 25%\">토익자격증</td>\r\n");
      out.write("			            <td style=\"width : 25%\">2022-07-06</td>\r\n");
      out.write("			            <td style=\"width : 25%\">대기</td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			    </tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("        <div class=\"col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("	<div class=\"card\">\r\n");
      out.write("		<h5 class=\"card-header\">자격증 제출</h5>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("			<table class=\"table table-hover\">\r\n");
      out.write("			    <thead>\r\n");
      out.write("			    	<tr>\r\n");
      out.write("			    		<th style=\"width: 30%\">토익자격증</th>\r\n");
      out.write("			    		<th style=\"width: 30%\">컴활자격증</th>\r\n");
      out.write("			    		<th style=\"width: 30%\">기타자격증</th>\r\n");
      out.write("			    	</tr>\r\n");
      out.write("			        <tr>\r\n");
      out.write("			            <td>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"input-group mb-3 justify-content-center\">\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<div class=\"card card-outline card-success\" style=\"width: 354px;\">\r\n");
      out.write("											<div class=\"card-header\">\r\n");
      out.write("												<h5 class=\"ml-3\" style=\"display:inline;line-height:40px;\"><strong>파일첨부 </strong></h5>\r\n");
      out.write("													&nbsp;&nbsp;<button class=\"btn btn-xs btn-light\"\r\n");
      out.write("													onclick=\"addFile_go1();\"	type=\"button\" id=\"addFileBtn1\">+</button>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"card-footer fileInput1\"></div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("			            </td>\r\n");
      out.write("			            <td>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"input-group mb-3 justify-content-center\">\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<div class=\"card card-outline card-success\" style=\"width: 354px;\">\r\n");
      out.write("											<div class=\"card-header\">\r\n");
      out.write("												<h5 class=\"ml-3\" style=\"display:inline;line-height:40px;\"><strong>파일첨부 </strong></h5>\r\n");
      out.write("													&nbsp;&nbsp;<button class=\"btn btn-xs btn-light\"\r\n");
      out.write("													onclick=\"addFile_go2();\"	type=\"button\" id=\"addFileBtn2\">+</button>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"card-footer fileInput2\"></div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("			            </td>\r\n");
      out.write("			            <td>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"input-group mb-3 justify-content-center\">\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<div class=\"card card-outline card-success\" style=\"width: 354px;\">\r\n");
      out.write("											<div class=\"card-header\">\r\n");
      out.write("												<h5 class=\"ml-3\" style=\"display:inline;line-height:40px;\"><strong>파일첨부 </strong></h5>\r\n");
      out.write("													&nbsp;&nbsp;<button class=\"btn btn-xs btn-light\"\r\n");
      out.write("													onclick=\"addFile_go3();\"	type=\"button\" id=\"addFileBtn3\">+</button>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"card-footer fileInput3\"></div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("			            </td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			    </thead>\r\n");
      out.write("			</table>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("	</div> \r\n");
      out.write("	<div class=\"row justify-content-end\">\r\n");
      out.write("			<button type=\"button\" class=\"btn-ml btn btn-primary mr-5\" onclick=\"\" >신청완료</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- 본문2 끝 -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ================================================= -->\r\n");
      out.write("<!-- MAIN-CONTENT 끝 -->\r\n");
      out.write("<!-- ================================================= -->\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"tab-pane fade active show\" id=\"outline-two\" role=\"tabpanel\" aria-labelledby=\"tab-outline-two\">\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("		<div class=\"card-body\">\r\n");
      out.write("<div class=\"main-content-jsp\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("             <div class=\"row\">\r\n");
      out.write("                 <div class=\"col-xl-2 col-lg-4 col-md-4 col-sm-4 col-12\">\r\n");
      out.write("                     <div class=\"text-center\">\r\n");
      out.write("<!--                          <img src=\"ddit/resources/img/jj.jpg\" alt=\"사용자이미지\" class=\"rounded-circle user-avatar-xxl\"> -->\r\n");
      out.write("                         <img src=\"ddit/resources/img/jj.jpg\" class=\"img-thumbnail mr-3\" alt=\"사용자이미지\">\r\n");
      out.write("                     </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("            	<div class=\"col-xl-10 col-lg-8 col-md-8 col-sm-8 col-12\">\r\n");
      out.write("                <div class=\"user-avatar-info\">\r\n");
      out.write("                    <!--  <div class=\"float-right\"><a href=\"#\" class=\"user-avatar-email text-secondary\">www.henrybarbara.com</a></div> -->\r\n");
      out.write("                    <div class=\"user-avatar-address\">\r\n");
      out.write("                        <div class=\"col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("								<div class=\"card\">\r\n");
      out.write("								<h3 class=\"card-header\"><i class=\"fas fa-user\"></i>&nbsp;&nbsp;학생기본정보</h3>\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("										<table class=\"table table-hover\">\r\n");
      out.write("										    <thead>\r\n");
      out.write("										        <tr>\r\n");
      out.write("										            <th style=\"width:10%\">학번</th>\r\n");
      out.write("										            <th style=\"width:10%\">이름</th>\r\n");
      out.write("										            <th style=\"width:15%\">학년</th>\r\n");
      out.write("										            <th style=\"width:15%\">분과대학</th>\r\n");
      out.write("										            <th style=\"width:15%\">학과</th>\r\n");
      out.write("										            <th style=\"width:25%\">입학일자</th>\r\n");
      out.write("										        </tr>\r\n");
      out.write("										    </thead>\r\n");
      out.write("										    <tbody>\r\n");
      out.write("										        <tr>\r\n");
      out.write("										            <td>학번</td>\r\n");
      out.write("										            <td>학년</td>\r\n");
      out.write("										            <td>학기</td>\r\n");
      out.write("										            <td>입학일</td>\r\n");
      out.write("										            <td>국적</td>\r\n");
      out.write("										            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("										        </tr>\r\n");
      out.write("										    </tbody>\r\n");
      out.write("										   \r\n");
      out.write("										    <thead>\r\n");
      out.write("										         <tr>\r\n");
      out.write("										            <th >전공</th>\r\n");
      out.write("										            <th >제2전공</th>\r\n");
      out.write("										            <th >제3전공</th>\r\n");
      out.write("										            <th >부전공</th>\r\n");
      out.write("										            <th >연락처</th>\r\n");
      out.write("										            <th >이메일</th>\r\n");
      out.write("										        </tr>\r\n");
      out.write("										    </thead>\r\n");
      out.write("										    <tbody>\r\n");
      out.write("										        <tr>\r\n");
      out.write("										            <td>전공</td>\r\n");
      out.write("										            <td>영문학</td>\r\n");
      out.write("										            <td>신청가능학점</td>\r\n");
      out.write("										            <td>2</td>\r\n");
      out.write("										            <td>011-2323-5444</td>\r\n");
      out.write("										            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("										        </tr>\r\n");
      out.write("										    </tbody>\r\n");
      out.write("										    <thead>\r\n");
      out.write("										         <tr>\r\n");
      out.write("										            <th >총이수학점</th>\r\n");
      out.write("										            <th >졸업이수학점</th>\r\n");
      out.write("										            <th >토익 자격증 여부</th>\r\n");
      out.write("										            <th >컴활 자격증 여부</th>\r\n");
      out.write("										            <th colspan=\"2\">주소</th>\r\n");
      out.write("										        </tr>\r\n");
      out.write("										    </thead>\r\n");
      out.write("										    <tbody>\r\n");
      out.write("										        <tr>\r\n");
      out.write("										            <td>학부</td>\r\n");
      out.write("										            <td>동아리</td>\r\n");
      out.write("										            <td>0</td>\r\n");
      out.write("										            <td>부전공</td>\r\n");
      out.write("										            <td colspan=\"2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.add1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.add2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("										        </tr>\r\n");
      out.write("										    </tbody>\r\n");
      out.write("										</table>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- 본문 1 -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"card\">\r\n");
      out.write("		<h3 class=\"card-header\">조기졸업/ 졸업유예 신청</h3>\r\n");
      out.write("		<div class=\"card-body\">\r\n");
      out.write("			<h5>신청목록</h5>\r\n");
      out.write("			<table class=\"table table-hover\">\r\n");
      out.write("			    <thead>\r\n");
      out.write("			        <tr>\r\n");
      out.write("			            <th style=\"width: 15%\">구분</th>\r\n");
      out.write("			            <th style=\"width: 15%\">이름</th>\r\n");
      out.write("			            <th style=\"width: 30%\">신청일자</th>\r\n");
      out.write("			            <th style=\"width: 10%\">진행여부</th>\r\n");
      out.write("			            <th style=\"width: 20%\">신청</th>\r\n");
      out.write("			            <th style=\"width: 10%\"></th>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			    </thead>\r\n");
      out.write("			    <tbody>\r\n");
      out.write("			        <tr>\r\n");
      out.write("			            <td>조기졸업</td>\r\n");
      out.write("			            <td>한태훈</td>\r\n");
      out.write("			            <td>2022-09-26</td>\r\n");
      out.write("			            <td>대기</td>\r\n");
      out.write("			            <td>\r\n");
      out.write("							<div class=\"input-group-append\">\r\n");
      out.write("								<select class=\"custom-select d-block w-100\" id=\"country\" required=\"\">\r\n");
      out.write("									<option>선택</option>\r\n");
      out.write("									<option>조기졸업</option>\r\n");
      out.write("									<option>졸업유예</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("			            </td>\r\n");
      out.write("			            <td>\r\n");
      out.write("			            	<div class=\"row justify-content-end\">\r\n");
      out.write("								<a href=\"#\" class=\"btn btn-outline-danger mr-5\">취소</a>\r\n");
      out.write("							</div>\r\n");
      out.write("			            </td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			    </tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("		<div class=\"row justify-content-end\">\r\n");
      out.write("			<button type=\"button\" class=\"btn-ml btn btn-primary mr-5\" onclick=\"\" >신청완료</button>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- 본문1 끝 -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- 본문 2 -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- 본문2 끝 -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ================================================= -->\r\n");
      out.write("<!-- MAIN-CONTENT 끝 -->\r\n");
      out.write("<!-- ================================================= -->\r\n");
      out.write("	</div>\r\n");
      out.write("</div>	\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ================================================= -->\r\n");
      out.write("<!-- MAIN-CONTENT -->\r\n");
      out.write("<!-- ================================================= -->\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	var dataNum1=0;\r\n");
      out.write("\r\n");
      out.write("	function addFile_go1(){\r\n");
      out.write("		//alert(\"click add btn\");\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		if($('.inputRow1').length >=5){\r\n");
      out.write("			alert(\"파일추가는 5개까지만 가능합니다.\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var div=$('<div>').addClass(\"inputRow1\").attr(\"data-no\",dataNum1).css(\"padding-top\",\"20px\");\r\n");
      out.write("		var input=$('<input>').attr({\"type\":\"file\",\"name\":\"uploadFile\"}).css(\"display\",\"inline\");\r\n");
      out.write("		\r\n");
      out.write("		var button=\"<button onclick='remove_go1(\"+dataNum1+\");' style='border:0;outline:0;' class='badge-danger' type='button'>X</button>\";\r\n");
      out.write("		\r\n");
      out.write("		div.append(input).append(button);\r\n");
      out.write("		$('.fileInput1').append(div);\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		dataNum1++;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function remove_go1(dataNum1){\r\n");
      out.write("		$('.inputRow1[data-no=\"'+dataNum1+'\"]').remove();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	var dataNum2=0;\r\n");
      out.write("\r\n");
      out.write("	function addFile_go2(){\r\n");
      out.write("		//alert(\"click add btn\");\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		if($('.inputRow2').length >=5){\r\n");
      out.write("			alert(\"파일추가는 5개까지만 가능합니다.\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var div=$('<div>').addClass(\"inputRow2\").attr(\"data-no\",dataNum2).css(\"padding-top\",\"20px\");\r\n");
      out.write("		var input=$('<input>').attr({\"type\":\"file\",\"name\":\"uploadFile\"}).css(\"display\",\"inline\");\r\n");
      out.write("		\r\n");
      out.write("		var button=\"<button onclick='remove_go2(\"+dataNum2+\");' style='border:0;outline:0;' class='badge-danger' type='button'>X</button>\";\r\n");
      out.write("		\r\n");
      out.write("		div.append(input).append(button);\r\n");
      out.write("		$('.fileInput2').append(div);\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		dataNum2++;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function remove_go2(dataNum2){\r\n");
      out.write("		$('.inputRow2[data-no=\"'+dataNum2+'\"]').remove();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	var dataNum3=0;\r\n");
      out.write("\r\n");
      out.write("	function addFile_go3(){\r\n");
      out.write("		//alert(\"click add btn\");\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		if($('.inputRow3').length >=5){\r\n");
      out.write("			alert(\"파일추가는 5개까지만 가능합니다.\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var div=$('<div>').addClass(\"inputRow3\").attr(\"data-no\",dataNum3).css(\"padding-top\",\"20px\");\r\n");
      out.write("		var input=$('<input>').attr({\"type\":\"file\",\"name\":\"uploadFile\"}).css(\"display\",\"inline\");\r\n");
      out.write("		\r\n");
      out.write("		var button=\"<button onclick='remove_go3(\"+dataNum3+\");' style='border:0;outline:0;' class='badge-danger' type='button'>X</button>\";\r\n");
      out.write("		\r\n");
      out.write("		div.append(input).append(button);\r\n");
      out.write("		$('.fileInput3').append(div);\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		dataNum3++;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function remove_go3(dataNum3){\r\n");
      out.write("		$('.inputRow3[data-no=\"'+dataNum3+'\"]').remove();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
