/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-11-27 02:18:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.prof.lec;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class attendList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1662347357502L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/tui-date-picker.css\" >\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/tui-example-style.css\" >\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- ================================================= -->\r\n");
      out.write("<!-- MAIN-CONTENT -->\r\n");
      out.write("<!-- ================================================= -->\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- 본문 1 -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- ================================================= -->\r\n");
      out.write("		<!-- 탭 -->\r\n");
      out.write("		<!-- ================================================= -->\r\n");
      out.write("		<div class=\"pills-regular col-xl-12\">\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<!-- 탭LIST 시작 -->\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<ul class=\"menuMove nav nav-pills mb-1\" id=\"pills-tab\" role=\"tablist\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					id=\"lecMain-tab\"\r\n");
      out.write("					onclick=\"pageMove('");
      out.print(request.getContextPath() );
      out.write("/prof/lec/main?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"\r\n");
      out.write("					data-toggle=\"pill\" href=\"#lecMain\"\r\n");
      out.write("					role=\"tab\" aria-controls=\"home\" aria-selected=\"false\">메인</a></li>\r\n");
      out.write("					\r\n");
      out.write("				<li class=\"menuMove nav-item\"><a class=\"nav-link active show\"\r\n");
      out.write("					id=\"lecAttend-tab\"\r\n");
      out.write("					onclick=\"pageMove('");
      out.print(request.getContextPath() );
      out.write("/prof/lec/attend/list.do?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"\r\n");
      out.write("					data-toggle=\"pill\" href=\"#lecAttend\"\r\n");
      out.write("					role=\"tab\" aria-controls=\"contact\" aria-selected=\"true\">출결관리</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"menuMove nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					id=\"lecMarks-tab\"\r\n");
      out.write("					onclick=\"pageMove('");
      out.print(request.getContextPath() );
      out.write("/prof/lec/marks/list.do?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"\r\n");
      out.write("					data-toggle=\"pill\" href=\"#lecMarks\"\r\n");
      out.write("					role=\"tab\" aria-controls=\"contact\" aria-selected=\"false\">성적관리</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				\r\n");
      out.write("				<li class=\"menuMove nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					id=\"lecMaterials-tab\"\r\n");
      out.write("					onclick=\"pageMove('");
      out.print(request.getContextPath() );
      out.write("/prof/lec/materials/list.do?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"\r\n");
      out.write("					data-toggle=\"pill\" href=\"#lecMaterials\"\r\n");
      out.write("					role=\"tab\" aria-controls=\"contact\" aria-selected=\"false\">학습자료</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<!-- 탭 LIST 끝 -->\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<!-- 탭 CONTENT 시작 -->\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("<!-- 				 onload=\"pageChanged()\"  -->\r\n");
      out.write("<!-- alert(this.contentWindow.location); -->\r\n");
      out.write("<!-- 				<iframe id=\"innerFrame\" -->\r\n");
      out.write("\r\n");
      out.write("<!-- 					scrolling=\"no\" style=\"border:1px dotted red; overflow-x:hidden; width:100%;height:93%;\"></iframe> -->\r\n");
      out.write("\r\n");
      out.write("			<div class=\"tab-content\" id=\"pills-tabContent\" style=\"padding:10px;\">\r\n");
      out.write("				<!-- 탭 1 시작 -->\r\n");
      out.write("				<div class=\"tab-pane fade\" id=\"lecMain\" role=\"tabpanel\" aria-labelledby=\"pills-lecMain-tab\">\r\n");
      out.write("					<p>텍스트1</p>\r\n");
      out.write("				</div> \r\n");
      out.write("				<!-- 탭 1 끝 -->\r\n");
      out.write("					\r\n");
      out.write("				<!-- 탭 2 시작 -->\r\n");
      out.write("				\r\n");
      out.write("				<!-- 탭 5 끝 -->\r\n");
      out.write("				<!-- 탭 6 시작 -->\r\n");
      out.write("				<div class=\"tab-pane fade active show\" id=\"lecAttend\" role=\"tabpanel\"\r\n");
      out.write("					aria-labelledby=\"pills-lecAttend-tab\" style=\"overflow:hidden; height:650px;\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<!-- 좌측달력 시작 -->\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<div class=\"card-body col col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"input-group d-flex justify-content-center\">\r\n");
      out.write("									<div class=\"tui-datepicker-input tui-datetime-input tui-has-focus\">\r\n");
      out.write("														<input type=\"text\" id=\"datepicker-input\" aria-label=\"Date-Time\" style=\" visibility:none;\">\r\n");
      out.write("										<span class=\"tui-ico-date\"></span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div id=\"wrapper\" style=\"position:absolute; left:13%; top:100%; margin-top: -1px;\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<!-- 좌측달력 끝 -->\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div id=\"oneAttendDiv\" style=\"position:absolute; top:400px; left:60px; display:block;\">\r\n");
      out.write("									<div class=\"card-body d-flex justify-content-center\" style=\"padding-bottom:0px;\">\r\n");
      out.write("										<h3 class=\"card-title border-bottom pb-2\" style=\"font-weight:bold\">개인별 출석 현황 : <span id=\"selectName\">&nbsp;&nbsp;이름&nbsp;</span></h3>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"card-body d-flex justify-content-end\"\r\n");
      out.write("										style=\"overflow-y:scroll; overflow-x:hidden; height:180px; padding-top:0px;\">\r\n");
      out.write("										<ul class=\"list-group\" id=\"onAttendUl\">\r\n");
      out.write("<!-- 											<li class=\"list-group-item d-flex justify-content-between align-items-center\"> -->\r\n");
      out.write("<!-- 											2022/11/1 (1주차) -->\r\n");
      out.write("<!-- 											<span class=\"badge badge-primary badge-pill\">출석</span> -->\r\n");
      out.write("<!-- 											</li> -->\r\n");
      out.write("<!-- 											<li class=\"list-group-item d-flex justify-content-between align-items-center\"> -->\r\n");
      out.write("<!-- 											2022/11/3 (1주차) -->\r\n");
      out.write("<!-- 											<span class=\"badge badge-danger badge-pill\">결석</span> -->\r\n");
      out.write("<!-- 											</li> -->\r\n");
      out.write("<!-- 											<li class=\"list-group-item d-flex justify-content-between align-items-center\"> -->\r\n");
      out.write("<!-- 											2022/11/7 (2주차) -->\r\n");
      out.write("<!-- 											<span class=\"badge badge-warning badge-pill\">지각</span> -->\r\n");
      out.write("<!-- 											</li> -->\r\n");
      out.write("<!-- 											<li class=\"list-group-item d-flex justify-content-between align-items-center\"> -->\r\n");
      out.write("<!-- 											2022/11/10 (2주차) -->\r\n");
      out.write("<!-- 											<span class=\"badge badge-primary badge-pill\">출석</span> -->\r\n");
      out.write("<!-- 											</li> -->\r\n");
      out.write("<!-- 											<li class=\"list-group-item d-flex justify-content-between align-items-center\"> -->\r\n");
      out.write("<!-- 											2022/11/10 (2주차) -->\r\n");
      out.write("<!-- 											<span class=\"badge badge-primary badge-pill\">출석</span> -->\r\n");
      out.write("<!-- 											</li> -->\r\n");
      out.write("										</ul>\r\n");
      out.write("<!-- 									<table border=\"1\"> -->\r\n");
      out.write("<!-- 										<tr> -->\r\n");
      out.write("<!-- 											<th>2022/11/1(월)</th> -->\r\n");
      out.write("<!-- 											<td>출석</td> -->\r\n");
      out.write("<!-- 										</tr> -->\r\n");
      out.write("<!-- 										<tr> -->\r\n");
      out.write("<!-- 											<th>2022/11/3(수)</th> -->\r\n");
      out.write("<!-- 											<td>지각</td> -->\r\n");
      out.write("<!-- 										</tr> -->\r\n");
      out.write("<!-- 										<tr> -->\r\n");
      out.write("<!-- 											<th>2022/11/7(금)</th> -->\r\n");
      out.write("<!-- 											<td>출석</td> -->\r\n");
      out.write("<!-- 										</tr> -->\r\n");
      out.write("<!-- 									</table> -->\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<!-- 우측 테이블 시작 -->\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<div class=\"card-body col col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12 ml-5\"\r\n");
      out.write("							style=\"position:relative; top:-70px; left:20%;\">\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<!-- 상단바 시작 -->\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<div class=\"row justify-content-between ml-2 mr-2\" style=\"\">\r\n");
      out.write("						<h3 class=\"d-flex align-items-center\"><i class=\"fas fa-calendar-check\"></i>\r\n");
      out.write("						&nbsp;&nbsp;&nbsp;<span id=\"selectDate\">");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("						<button type=\"button\" id=\"insertBtn\">초기데이터insert용</button>\r\n");
      out.write("						</h3>\r\n");
      out.write("							<div class=\"row justify-content-end m-2\">\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-md btn-primary\"\r\n");
      out.write("								onclick=\"f_modifyList();\">일괄 저장</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<!-- 상단바 끝 -->\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<div id=\"listDiv\" style=\"overflow-y:scroll; overflow-x:hidden; height:565px;\">\r\n");
      out.write("								<!-- ajax -->\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- ================================================= -->\r\n");
      out.write("							<!-- 게시판 끝 -->\r\n");
      out.write("							<!-- ================================================= -->\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("					\r\n");
      out.write("							<!-- ================================================= -->\r\n");
      out.write("							<!-- 페이지네이션 시작 -->\r\n");
      out.write("							<!-- ================================================= -->\r\n");
      out.write("							<!-- ================================================= -->\r\n");
      out.write("							<!-- 페이지네이션 끝 -->\r\n");
      out.write("							<!-- ================================================= -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>	\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 탭 6 끝 -->\r\n");
      out.write("				<!-- 탭 7 시작 -->\r\n");
      out.write("				<div class=\"tab-pane fade\" id=\"lecMarks\" role=\"tabpanel\" aria-labelledby=\"pills-lecMarks-tab\">\r\n");
      out.write("					<p>텍스트7</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 탭 7 끝 -->\r\n");
      out.write("				<!-- 탭 8 시작 -->\r\n");
      out.write("				<div class=\"tab-pane fade\" id=\"lecMaterials\" role=\"tabpanel\" aria-labelledby=\"pills-lecMaterials-tab\">\r\n");
      out.write("					<p>텍스트8</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 탭 8 끝 -->\r\n");
      out.write("				<!-- 탭 9 시작 -->\r\n");
      out.write("			\r\n");
      out.write("				<!-- 탭 9 끝 -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<!-- 탭 CONTENT 끝 -->\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- ================================================= -->\r\n");
      out.write("		<!-- 탭 끝 -->\r\n");
      out.write("		<!-- ================================================= -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- 본문1 끝 -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ================================================= -->\r\n");
      out.write("<!-- MAIN-CONTENT 끝 -->\r\n");
      out.write("<!-- ================================================= -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/tui-date-picker.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("window.onload = function(){\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type:'get',\r\n");
      out.write("		url:'");
      out.print(request.getContextPath());
      out.write("/prof/lec/attend/attendList?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("		success: (rslt)=>{\r\n");
      out.write("// 			alert(rslt);\r\n");
      out.write("			//리스트뿌리기;\r\n");
      out.write("			if(rslt.length == 0){\r\n");
      out.write("				document.querySelector('#listDiv').innerHTML=\"출석일이 아닙니다\";\r\n");
      out.write("			}\r\n");
      out.write("			printData(rslt);\r\n");
      out.write("			\r\n");
      out.write("			var v_selectDate = new Date(rslt[0].attendDate);\r\n");
      out.write("			var v_date = f_transFormatToDate(v_selectDate);\r\n");
      out.write("// 			alert(v_date);\r\n");
      out.write("			document.querySelector('#selectDate').innerHTML = v_date;\r\n");
      out.write("// 			datepicker.setDate(v_selectDate);\r\n");
      out.write("\r\n");
      out.write("			var datepicker = new tui.DatePicker('#wrapper', {\r\n");
      out.write("			    date: v_selectDate,\r\n");
      out.write("			    input: {\r\n");
      out.write("			        element: '#datepicker-input',\r\n");
      out.write("			        format: 'yyyy-MM-dd'\r\n");
      out.write("			    },\r\n");
      out.write("			    showAlways: true\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			datepicker.on('change', () => {\r\n");
      out.write("//			 	alert('ajax로 오른쪽 테이블이 변경됩니다</br>오늘날짜는 : ' + datepicker.getDate());\r\n");
      out.write("				var v_selectDate = datepicker.getDate();\r\n");
      out.write("				console.log(\"날짜서냍ㄱ\",v_selectDate);\r\n");
      out.write("				var v_date = f_transFormatToDate(v_selectDate);\r\n");
      out.write("				console.log(\"v_selectDateㄱ\",v_date);\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					type:'get',\r\n");
      out.write("					url:'");
      out.print(request.getContextPath());
      out.write("/prof/lec/attend/attendList?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&attendDate='+v_date,\r\n");
      out.write("					success: (rslt)=>{\r\n");
      out.write("			 			console.log(rslt);\r\n");
      out.write("						//리스트뿌리기;\r\n");
      out.write("						if(rslt.length == 0){\r\n");
      out.write("							alert(\"출석일이 아닙니다\");\r\n");
      out.write("							document.querySelector('#selectDate').innerHTML = v_date;\r\n");
      out.write("							printData();\r\n");
      out.write("							return;\r\n");
      out.write("						}\r\n");
      out.write("						printData(rslt);\r\n");
      out.write("						\r\n");
      out.write("						var rslt_selectDate = new Date(rslt[0].attendDate);\r\n");
      out.write("						console.log(\"rslt_selectDate\",rslt_selectDate);\r\n");
      out.write("						var rslt_date = f_transFormatToDate(rslt_selectDate);\r\n");
      out.write("						console.log(\"rslt_date\",rslt_date);\r\n");
      out.write("						document.querySelector('#selectDate').innerHTML = rslt_date;\r\n");
      out.write("//		 				datepicker.setDate(rslt_selectDate);\r\n");
      out.write("// 						alert(\"바뀜\");\r\n");
      out.write("\r\n");
      out.write("					},\r\n");
      out.write("					error: ()=>{\r\n");
      out.write("						AjaxErrorSecurityRedirectHandler(error.status);\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			//insert\r\n");
      out.write("			let v_insertBtn = document.querySelector('#insertBtn');\r\n");
      out.write("			v_insertBtn.addEventListener('click',function(){\r\n");
      out.write("				var v_selectDate = datepicker.getDate();\r\n");
      out.write("				var v_lecCode = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("// 				console.log(v_selectDate);\r\n");
      out.write("				\r\n");
      out.write("				var sendData = {\r\n");
      out.write("						\"attendDate\":v_selectDate,\r\n");
      out.write("						\"lecCd\":v_lecCode\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					type:'post',\r\n");
      out.write("					url:'");
      out.print(request.getContextPath());
      out.write("/prof/lec/attend/regist',\r\n");
      out.write("					data: JSON.stringify(sendData),\r\n");
      out.write("					contentType:'application/json',\r\n");
      out.write("					success: (rslt) => {\r\n");
      out.write("						alert('등록성공');\r\n");
      out.write("						location.replace(location.href);\r\n");
      out.write("					},\r\n");
      out.write("					error: () => {\r\n");
      out.write("						AjaxErrorSecurityRedirectHandler(error.status);\r\n");
      out.write("					}\r\n");
      out.write("							\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		},\r\n");
      out.write("		error: ()=>{\r\n");
      out.write("			AjaxErrorSecurityRedirectHandler(error.status);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("// 	var v_setDate = document.querySelector('#selectDate').innerHTML;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var printData = (attendList) => {\r\n");
      out.write("	var v_tableStr =\r\n");
      out.write("	`<table class=\"table table-hover\">\r\n");
      out.write("		<thead>\r\n");
      out.write("			<tr style=\"position: sticky; top: -1px; background-color: white; z-index: 99;\">\r\n");
      out.write("				<th>순번</th>\r\n");
      out.write("				<th style=\"width:10%\">학번</th>\r\n");
      out.write("				<th>이름</th>\r\n");
      out.write("				<th style=\"width:12%\">출석</th> \r\n");
      out.write("				<th style=\"width:12%\">결석</th>\r\n");
      out.write("				<th style=\"width:12%\">지각</th>\r\n");
      out.write("				<th style=\"width:12%\">조퇴</th>\r\n");
      out.write("				<th>저장</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</thead>\r\n");
      out.write("		<tbody style=\"overflow-y: scroll;\">`;\r\n");
      out.write("		if(!attendList){\r\n");
      out.write("				v_tableStr += \r\n");
      out.write("				`<tr>\r\n");
      out.write("					<td colspan=\"8\">출석 데이터가 없습니다</td>\r\n");
      out.write("				</tr>`;\r\n");
      out.write("			\r\n");
      out.write("		}else{\r\n");
      out.write("			for(i=0; i<attendList.length; i++){\r\n");
      out.write("				v_tableStr += \r\n");
      out.write("				`<tr class=\"attendStuList\" onclick=\"f_stuAttendList(event);\">\r\n");
      out.write("					<td>`+(parseInt(i)+1)+`</td>\r\n");
      out.write("					<td class=\"stuCd\" id=\"${attendList[i].stuCd}\">${attendList[i].stuCd}</td>\r\n");
      out.write("					<td class=\"stuName\" id=\"${attendList[i].name}\">${attendList[i].name}</td>\r\n");
      out.write("					<td colspan=\"4\" >\r\n");
      out.write("						<div class=\"row justify-content-between ml-4 mr-3\">`;\r\n");
      out.write("						\r\n");
      out.write("							if(attendList[i].attendStatusCd == 'attend'){\r\n");
      out.write("								v_tableStr +=\r\n");
      out.write("								`<div>\r\n");
      out.write("								<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("									<input type=\"radio\" name=\"${attendList[i].attendSeq}\" value=\"attend\" \r\n");
      out.write("										style=\"left:8px\" class=\"attend custom-control-input\" checked>\r\n");
      out.write("										<span class=\"custom-control-label\">출석</span>\r\n");
      out.write("								</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("								<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("									<input type=\"radio\" name=\"${attendList[i].attendSeq }\" value=\"absent\"\r\n");
      out.write("										class=\"absent custom-control-input\">\r\n");
      out.write("										<span class=\"custom-control-label\">결석</span>\r\n");
      out.write("								</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("								<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("									<input type=\"radio\" name=\"${attendList[i].attendSeq }\" value=\"late\"\r\n");
      out.write("										class=\"late custom-control-input\">\r\n");
      out.write("										<span class=\"custom-control-label\">지각</span>\r\n");
      out.write("								</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("								<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("									<input type=\"radio\" name=\"${attendList[i].attendSeq }\" value=\"le\"\r\n");
      out.write("										class=\"le custom-control-input\">\r\n");
      out.write("										<span class=\"custom-control-label\">조퇴</span>\r\n");
      out.write("								</label>\r\n");
      out.write("								</div>`;\r\n");
      out.write("							}else if(attendList[i].attendStatusCd == 'absent'){\r\n");
      out.write("								v_tableStr +=\r\n");
      out.write("									`<div>\r\n");
      out.write("									<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("										<input type=\"radio\" name=\"${attendList[i].attendSeq}\" value=\"attend\" \r\n");
      out.write("											style=\"left:8px\" class=\"attend custom-control-input\" >\r\n");
      out.write("											<span class=\"custom-control-label\">출석</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("									<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("										<input type=\"radio\" name=\"${attendList[i].attendSeq }\" value=\"absent\"\r\n");
      out.write("											class=\"absent custom-control-input\" checked>\r\n");
      out.write("											<span class=\"custom-control-label\">결석</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("									<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("										<input type=\"radio\" name=\"${attendList[i].attendSeq }\" value=\"late\"\r\n");
      out.write("											class=\"late custom-control-input\">\r\n");
      out.write("											<span class=\"custom-control-label\">지각</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("									<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("										<input type=\"radio\" name=\"${attendList[i].attendSeq }\" value=\"le\"\r\n");
      out.write("											class=\"le custom-control-input\">\r\n");
      out.write("											<span class=\"custom-control-label\">조퇴</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									</div>`;\r\n");
      out.write("							}else if(attendList[i].attendStatusCd == 'late'){\r\n");
      out.write("								v_tableStr +=\r\n");
      out.write("									`<div>\r\n");
      out.write("									<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("										<input type=\"radio\" name=\"${attendList[i].attendSeq}\" value=\"attend\" \r\n");
      out.write("											style=\"left:8px\" class=\"attend custom-control-input\" >\r\n");
      out.write("											<span class=\"custom-control-label\">출석</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("									<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("										<input type=\"radio\" name=\"${attendList[i].attendSeq }\" value=\"absent\"\r\n");
      out.write("											class=\"absent custom-control-input\">\r\n");
      out.write("											<span class=\"custom-control-label\">결석</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("									<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("										<input type=\"radio\" name=\"${attendList[i].attendSeq }\" value=\"late\"\r\n");
      out.write("											class=\"late custom-control-input\" checked>\r\n");
      out.write("											<span class=\"custom-control-label\">지각</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("									<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("										<input type=\"radio\" name=\"${attendList[i].attendSeq }\" value=\"le\"\r\n");
      out.write("											class=\"le custom-control-input\">\r\n");
      out.write("											<span class=\"custom-control-label\">조퇴</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									</div>`;\r\n");
      out.write("							}else if(attendList[i].attendStatusCd == 'le'){\r\n");
      out.write("								v_tableStr +=\r\n");
      out.write("									`<div>\r\n");
      out.write("									<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("										<input type=\"radio\" name=\"${attendList[i].attendSeq}\" value=\"attend\" \r\n");
      out.write("											style=\"left:8px\" class=\"attend custom-control-input\" >\r\n");
      out.write("											<span class=\"custom-control-label\">출석</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("									<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("										<input type=\"radio\" name=\"${attendList[i].attendSeq }\" value=\"absent\"\r\n");
      out.write("											class=\"absent custom-control-input\">\r\n");
      out.write("											<span class=\"custom-control-label\">결석</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("									<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("										<input type=\"radio\" name=\"${attendList[i].attendSeq }\" value=\"late\"\r\n");
      out.write("											class=\"late custom-control-input\">\r\n");
      out.write("											<span class=\"custom-control-label\">지각</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("									<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("										<input type=\"radio\" name=\"${attendList[i].attendSeq }\" value=\"le\"\r\n");
      out.write("											class=\"le custom-control-input\" checked>\r\n");
      out.write("											<span class=\"custom-control-label\">조퇴</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									</div>`;\r\n");
      out.write("							}\r\n");
      out.write("					v_tableStr +=\r\n");
      out.write("						`</div>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<button class=\"btn btn-primary btn-sm\" type=\"button\" id=\"${attendList[i].attendSeq }\"\r\n");
      out.write("						onclick=\"f_modifyAttend(event);\">저장\r\n");
      out.write("						</button>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>`;\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		v_tableStr += `</tbody>\r\n");
      out.write("	</table>`;\r\n");
      out.write("	\r\n");
      out.write("	document.querySelector('#listDiv').innerHTML=v_tableStr;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//tr클릭\r\n");
      out.write("function f_stuAttendList(e){\r\n");
      out.write("\r\n");
      out.write("	var v_stuName = e.currentTarget.children[2].getAttribute('id');\r\n");
      out.write("    var v_stuCd = e.currentTarget.children[1].getAttribute('id');\r\n");
      out.write("	\r\n");
      out.write("    document.querySelector('#selectName').innerHTML = v_stuName;\r\n");
      out.write("    \r\n");
      out.write("    $.ajax({\r\n");
      out.write("    	type:'get',\r\n");
      out.write("    	url:'");
      out.print(request.getContextPath());
      out.write("/prof/lec/attend/stuAttendList?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&stuCd='+v_stuCd,\r\n");
      out.write("    	success: (rslt)=>{\r\n");
      out.write("    		console.log(rslt);\r\n");
      out.write("    		var v_ulStr = \"\";\r\n");
      out.write("    		for(i=0; i<rslt.length; i++){\r\n");
      out.write("    			var v_getDate = new Date(rslt[i].attendDate);\r\n");
      out.write("	    		var v_attendDate = f_transFormatToDate(v_getDate);\r\n");
      out.write("// 	    		alert(v_attendDate);\r\n");
      out.write("    			if(rslt[i].attendStatusCd == 'attend'){\r\n");
      out.write("	    			v_ulStr += \r\n");
      out.write("		    		`<li class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("	    			${v_attendDate}&nbsp;(${rslt[i].semeWeek}주차)&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("					<span class=\"badge badge-primary badge-pill\">출석</span>\r\n");
      out.write("					</li>`;\r\n");
      out.write("    			}else if(rslt[i].attendStatusCd == 'absent'){\r\n");
      out.write("	    			v_ulStr += \r\n");
      out.write("		    		`<li class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("					${v_attendDate}&nbsp;(${rslt[i].semeWeek}주차)&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("					<span class=\"badge badge-danger badge-pill\">결석</span>\r\n");
      out.write("					</li>`;\r\n");
      out.write("    				\r\n");
      out.write("    			}else if(rslt[i].attendStatusCd == 'late'){\r\n");
      out.write("	    			v_ulStr += \r\n");
      out.write("		    		`<li class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("					${v_attendDate}&nbsp;(${rslt[i].semeWeek}주차)&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("					<span class=\"badge badge-warning badge-pill\">지각</span>\r\n");
      out.write("					</li>`;\r\n");
      out.write("    			}else if(rslt[i].attendStatusCd == 'le'){\r\n");
      out.write("	    			v_ulStr += \r\n");
      out.write("		    		`<li class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("					${v_attendDate}&nbsp;(${rslt[i].semeWeek}주차)&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("					<span class=\"badge badge-warning badge-pill\">조퇴</span>\r\n");
      out.write("					</li>`;\r\n");
      out.write("    				\r\n");
      out.write("    			}\r\n");
      out.write("    			\r\n");
      out.write("    			document.querySelector('#onAttendUl').innerHTML = v_ulStr;\r\n");
      out.write("    		}\r\n");
      out.write("    		\r\n");
      out.write("	    },\r\n");
      out.write("		error: ()=>{\r\n");
      out.write("			AjaxErrorSecurityRedirectHandler(error.status);\r\n");
      out.write("		}\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function f_modifyAttend(e){\r\n");
      out.write("    e.stopPropagation(); //부모까지 이벤트 번질때\r\n");
      out.write("    var v_stuName = e.currentTarget.parentElement.parentElement.children[2].getAttribute('id');\r\n");
      out.write("    var v_attendSeq = e.currentTarget.getAttribute('id');\r\n");
      out.write("    \r\n");
      out.write("	var v_attendStatus = $('input[name='+v_attendSeq+']:checked').val();\r\n");
      out.write("	console.log(\"라디오체크찾기\",v_attendStatus);\r\n");
      out.write("	\r\n");
      out.write("	var sendData = {\r\n");
      out.write("			attendSeq:v_attendSeq,\r\n");
      out.write("			attendStatusCd:v_attendStatus\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type:'put',\r\n");
      out.write("		url:'");
      out.print(request.getContextPath());
      out.write("/prof/lec/attend/modify',\r\n");
      out.write("		data:JSON.stringify(sendData),\r\n");
      out.write("		contentType:'application/json',\r\n");
      out.write("		success: (rslt)=> {\r\n");
      out.write("			\r\n");
      out.write("			Swal.fire(\r\n");
      out.write("					  v_stuName+'학생의 출석이 저장됐습니다.',\r\n");
      out.write("					  '',\r\n");
      out.write("					  'success'\r\n");
      out.write("					)\r\n");
      out.write("		},\r\n");
      out.write("		error: ()=> {\r\n");
      out.write("			AjaxErrorSecurityRedirectHandler(error.status);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function f_modifyList(){\r\n");
      out.write("	\r\n");
      out.write("	var v_list = [];\r\n");
      out.write("	var v_tr = document.querySelectorAll(\".attendStuList\");\r\n");
      out.write("	//console.log(\"trs\",v_tr)\r\n");
      out.write("	for(var i=0; i<v_tr.length; i++){\r\n");
      out.write("		//var hakbun = v_tr[i].children[0].innerHTML;\r\n");
      out.write("		//console.log(\"tr\",v_tr[i]);\r\n");
      out.write("		\r\n");
      out.write("		var v_sequence = v_tr[i].querySelector(\"button\").getAttribute(\"id\");\r\n");
      out.write("		//console.log(\"시퀀스:\",sequence);\r\n");
      out.write("		var v_status = v_tr[i].querySelector(\"input[type=radio]:checked\").value;\r\n");
      out.write("		//console.log(\"스테이터스\",status);\r\n");
      out.write("\r\n");
      out.write("		var v_json = {};\r\n");
      out.write("		v_json.attendSeq = v_sequence;\r\n");
      out.write("		v_json.attendStatusCd = v_status;\r\n");
      out.write("		v_list.push(v_json);\r\n");
      out.write("	}\r\n");
      out.write("	console.log(v_list);\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type:'put',\r\n");
      out.write("		url:'");
      out.print(request.getContextPath());
      out.write("/prof/lec/attend/modifyList',\r\n");
      out.write("		data:JSON.stringify(v_list),\r\n");
      out.write("		contentType:'application/json',\r\n");
      out.write("		success: (rslt)=>{\r\n");
      out.write("			alert('전체 수강생의 출석이 저장됐습니다.');\r\n");
      out.write("		},\r\n");
      out.write("		error: ()=>{\r\n");
      out.write("			AjaxErrorSecurityRedirectHandler(error.status);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/prof/lec/attendList.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cpath");
      // /WEB-INF/views/prof/lec/attendList.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/prof/lec/attendList.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/views/prof/lec/attendList.jsp(162,46) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${attendDate }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/prof/lec/attendList.jsp(162,46) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy/MM/dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }
}
