/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-11-27 02:18:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.prof.lec;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lecBoardMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1662347357502L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/tui-date-picker.css\" >\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/tui-example-style.css\" >\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.7/handlebars.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- MAIN-CONTENT -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<!-- ================================================= -->\r\n");
      out.write("		<!-- 본문 1 -->\r\n");
      out.write("		<!-- ================================================= -->\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<!-- 탭 -->\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<div class=\"pills-regular col-xl-12\">\r\n");
      out.write("\r\n");
      out.write("				<!-- ================================================= -->\r\n");
      out.write("				<!-- 탭LIST 시작 -->\r\n");
      out.write("				<!-- ================================================= -->\r\n");
      out.write("				<ul class=\"menuMove nav nav-pills mb-1\" id=\"pills-tab\" role=\"tablist\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active show\"\r\n");
      out.write("						id=\"lecMain-tab\"\r\n");
      out.write("						onclick=\"pageMove('");
      out.print(request.getContextPath() );
      out.write("/prof/lec/main?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"\r\n");
      out.write("						data-toggle=\"pill\" href=\"#\"\r\n");
      out.write("						role=\"tab\" aria-controls=\"home\" aria-selected=\"true\">메인</a></li>\r\n");
      out.write("						\r\n");
      out.write("					\r\n");
      out.write("					<li class=\"menuMove nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						id=\"lecAttend-tab\"\r\n");
      out.write("						onclick=\"pageMove('");
      out.print(request.getContextPath() );
      out.write("/imsi/attend/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"\r\n");
      out.write("						data-toggle=\"pill\" href=\"#\"\r\n");
      out.write("						role=\"tab\" aria-controls=\"contact\" aria-selected=\"false\">출결관리</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"menuMove nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						id=\"lecMarks-tab\"\r\n");
      out.write("						onclick=\"pageMove('");
      out.print(request.getContextPath() );
      out.write("/prof/lec/marks/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"\r\n");
      out.write("						data-toggle=\"pill\" href=\"#\"\r\n");
      out.write("						role=\"tab\" aria-controls=\"contact\" aria-selected=\"false\">성적관리</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("					<li class=\"menuMove nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						id=\"lecMaterials-tab\"\r\n");
      out.write("						onclick=\"pageMove('");
      out.print(request.getContextPath() );
      out.write("/prof/lec/materials/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"\r\n");
      out.write("						data-toggle=\"pill\" href=\"#\"\r\n");
      out.write("						role=\"tab\" aria-controls=\"contact\" aria-selected=\"false\">학습자료</a></li>\r\n");
      out.write("				\r\n");
      out.write("				</ul>\r\n");
      out.write("				<!-- ================================================= -->\r\n");
      out.write("				<!-- 탭 LIST 끝 -->\r\n");
      out.write("				<!-- ================================================= -->\r\n");
      out.write("				\r\n");
      out.write("				<!-- ================================================= -->\r\n");
      out.write("				<!-- 탭 CONTENT 시작 -->\r\n");
      out.write("				<!-- ================================================= -->\r\n");
      out.write("<!-- 				 onload=\"pageChanged()\"  -->\r\n");
      out.write("<!-- alert(this.contentWindow.location); -->\r\n");
      out.write("<!-- 				<iframe id=\"innerFrame\" -->\r\n");
      out.write("\r\n");
      out.write("<!-- 					scrolling=\"no\" style=\"border:1px dotted red; overflow-x:hidden; width:100%;height:93%;\"></iframe> -->\r\n");
      out.write("\r\n");
      out.write("				<div class=\"tab-content\" id=\"pills-tabContent\">\r\n");
      out.write("					<!-- 탭 1 시작 -->\r\n");
      out.write("					<div class=\"tab-pane fade active show\" id=\"lecMain\" role=\"tabpanel\" aria-labelledby=\"pills-lecMain-tab\">\r\n");
      out.write("					\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<!-- 본문 1 -->\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("						\r\n");
      out.write("					        <div class=\"col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("								<div class=\"card\" style=\"height:489px;\">\r\n");
      out.write("									<div class=\"card-body\" id=\"noticeCardBody\">\r\n");
      out.write("									\r\n");
      out.write("									</div>\r\n");
      out.write("										<div class=\"card-footer\">\r\n");
      out.write("										<form id='notjobForm'>\r\n");
      out.write("											<input id ='notPage' type='hidden' name='assPage' value='' />\r\n");
      out.write("											<input id='notSearchType' type='hidden' name='searchType' value='' />\r\n");
      out.write("											<input id='notKeyword' type='hidden' name='keyword' value='' />\r\n");
      out.write("											<input id='notLecCd' type='hidden' name='lecCd' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' />\r\n");
      out.write("										</form>\r\n");
      out.write("									<ul id=\"noticeCardFooter\" class=\"pagination justify-content-center m-0\" >\r\n");
      out.write("									</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("										\r\n");
      out.write("									\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("							<div class=\"col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("								<div class=\"card\" style=\"height:489px;\">\r\n");
      out.write("									<div class=\"card-body\" id=\"qnaCardBody\">\r\n");
      out.write("									</div>\r\n");
      out.write("										<div class=\"card-footer\">\r\n");
      out.write("										<form id='qnajobForm'>\r\n");
      out.write("											<input id ='qnaPage' type='hidden' name='qnaPage' value='' />\r\n");
      out.write("											<input id='qnaSearchType' type='hidden' name='searchType' value='' />\r\n");
      out.write("											<input id='qnaKeyword' type='hidden' name='keyword' value='' />\r\n");
      out.write("											<input id='qnaLecCd' type='hidden' name='lecCd' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' />\r\n");
      out.write("										</form>\r\n");
      out.write("									<ul id=\"qnaCardFooter\" class=\"pagination justify-content-center m-0\" >\r\n");
      out.write("									</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("										<!-- 페이지네이션 끝 -->\r\n");
      out.write("										<!-- ================================================= -->					\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("							\r\n");
      out.write("						</div> \r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<!-- 본문1 끝 -->\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("					\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<!-- 과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제 -->\r\n");
      out.write("						<!-- 과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제 -->\r\n");
      out.write("						<!-- 과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제과제 -->\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("						\r\n");
      out.write("					        <div class=\"col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("								<div class=\"card\" style=\"height:489px;\">\r\n");
      out.write("									<div class=\"card-body\" id=\"assignmentCardBody\">\r\n");
      out.write("									\r\n");
      out.write("										\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"card-footer\">\r\n");
      out.write("										<form id='assjobForm'>\r\n");
      out.write("											<input id ='assPage' type='hidden' name='assPage' value='' />\r\n");
      out.write("											<input id='assSearchType' type='hidden' name='searchType' value='' />\r\n");
      out.write("											<input id='assKeyword' type='hidden' name='keyword' value='' />\r\n");
      out.write("											<input id='assLecCd' type='hidden' name='lecCd' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' />\r\n");
      out.write("										</form>\r\n");
      out.write("									<ul id=\"assignmentCardFooter\" class=\"pagination justify-content-center m-0\" >\r\n");
      out.write("									</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							<!-- 일정 시작 -->\r\n");
      out.write("					        <div class=\"col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("								<div class=\"card\" style=\"height:489px;\">\r\n");
      out.write("									<div class=\"card-body\">\r\n");
      out.write("										<h2><i class=\"fas fa-calendar-check\"></i>&nbsp;&nbsp;일정</h2>\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("										<!-- 등록칸 시작 -->\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("										<div class=\"input-group mt-3 mb-3 justify-content-center align-items-center\">\r\n");
      out.write("										\r\n");
      out.write("											<span style=\"font-size:1.2em;\"><strong>구분</strong></span>&nbsp;&nbsp;\r\n");
      out.write("											<select class=\"form-control col-md-2\" name=\"perPageNum\" id=\"examDiv\">					  		  		\r\n");
      out.write("										  		<option value=\"\">선택</option>\r\n");
      out.write("										  		<option value=\"mid\">중간고사</option>\r\n");
      out.write("										  		<option value=\"fin\">기말고사</option>\r\n");
      out.write("										  		<option value=\"mini\">쪽지시험</option>\r\n");
      out.write("										  		\r\n");
      out.write("										  	</select>\r\n");
      out.write("											&nbsp;&nbsp;&nbsp;\r\n");
      out.write("											<span style=\"font-size:1.2em;\"><strong>일시</strong></span>&nbsp;&nbsp;\r\n");
      out.write("											<div class=\"code-html\">\r\n");
      out.write("										        <div class=\"tui-datepicker-input tui-datetime-input tui-has-focus\">\r\n");
      out.write("										            <input type=\"text\" id=\"datepicker-input\" aria-label=\"Date-Time\">\r\n");
      out.write("										            <span class=\"tui-ico-date\"></span>\r\n");
      out.write("										        </div>\r\n");
      out.write("										        <div id=\"datepicker-div\"  style=\"position: relative; background-color:white; z-index: 9999; margin-top: -1px;\"></div>\r\n");
      out.write("										    </div>\r\n");
      out.write("										  	\r\n");
      out.write("											&nbsp;&nbsp;&nbsp;\r\n");
      out.write("											<span style=\"font-size:1.2em;\"><strong>강의실</strong></span>&nbsp;&nbsp;\r\n");
      out.write("										 	<input type=\"text\" class=\"form-control col-md-2\" id=\"classroom\" name=\"classroom\" id=\"searchType\" style=\"height:38px;\">\r\n");
      out.write("										 	&nbsp;&nbsp;&nbsp;\r\n");
      out.write("											<button class=\"btn btn-sm btn-primary\" type=\"button\" onclick=\"f_regist(event)\">등록</button>\r\n");
      out.write("										</div>\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("										<!-- 등록칸 끝 -->\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("										\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("										<!-- 게시판 시작 -->\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("										\r\n");
      out.write("											<table class=\"table table-hover\">\r\n");
      out.write("												<thead>\r\n");
      out.write("													<tr style=\"background-color:rgba(102,178,255,0.2)\">\r\n");
      out.write("														<th>종류</th>\r\n");
      out.write("														<th>일시</th>\r\n");
      out.write("														<th>강의실명</th>\r\n");
      out.write("														<th style=\"width:12%\">수정</th>\r\n");
      out.write("														<th style=\"width:12%\">삭제</th>\r\n");
      out.write("													</tr>\r\n");
      out.write("												</thead>\r\n");
      out.write("												<tbody id=\"examTbody\">\r\n");
      out.write("													\r\n");
      out.write("								\r\n");
      out.write("													\r\n");
      out.write("												</tbody>\r\n");
      out.write("											</table>\r\n");
      out.write("														</div>	\r\n");
      out.write("														\r\n");
      out.write("											<!-- ================================================= -->\r\n");
      out.write("											<!-- 게시판 끝 -->\r\n");
      out.write("											<!-- ================================================= -->\r\n");
      out.write("											\r\n");
      out.write("									\r\n");
      out.write("											<!-- ================================================= -->\r\n");
      out.write("											<!-- 페이지네이션 시작 -->\r\n");
      out.write("											<!-- ================================================= -->\r\n");
      out.write("											<div class=\"card-footer\">\r\n");
      out.write("											      <nav aria-label=\"Page navigation example\">\r\n");
      out.write("											         <ul class=\"pagination justify-content-center m-0\" id=\"examPagenation\">\r\n");
      out.write("											         </ul>\r\n");
      out.write("											            \r\n");
      out.write("											      </nav>\r\n");
      out.write("											</div>\r\n");
      out.write("											<!-- ================================================= -->\r\n");
      out.write("											<!-- 페이지네이션 끝 -->\r\n");
      out.write("											<!-- ================================================= -->\r\n");
      out.write("								      \r\n");
      out.write("									   \r\n");
      out.write("									   \r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 일정 시작 -->\r\n");
      out.write("								\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("						<!-- 본문2 끝 -->\r\n");
      out.write("						<!-- ================================================= -->\r\n");
      out.write("				\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("					</div> \r\n");
      out.write("			\r\n");
      out.write("					<!-- 탭 5 끝 -->\r\n");
      out.write("					<!-- 탭 6 시작 -->\r\n");
      out.write("					<div class=\"tab-pane fade\" id=\"lecAttend\" role=\"tabpanel\" aria-labelledby=\"pills-lecAttend-tab\">\r\n");
      out.write("						<p>텍스트6</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 탭 6 끝 -->\r\n");
      out.write("					<!-- 탭 7 시작 -->\r\n");
      out.write("					<div class=\"tab-pane fade\" id=\"lecMarks\" role=\"tabpanel\" aria-labelledby=\"pills-lecMarks-tab\">\r\n");
      out.write("						<p>텍스트7</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 탭 7 끝 -->\r\n");
      out.write("					<!-- 탭 8 시작 -->\r\n");
      out.write("					<div class=\"tab-pane fade\" id=\"lecMaterials\" role=\"tabpanel\" aria-labelledby=\"pills-lecMaterials-tab\">\r\n");
      out.write("						<p>텍스트8</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 탭 8 끝 -->\r\n");
      out.write("					<!-- 탭 9 시작 -->\r\n");
      out.write("				\r\n");
      out.write("					<!-- 탭 9 끝 -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- ================================================= -->\r\n");
      out.write("				<!-- 탭 CONTENT 끝 -->\r\n");
      out.write("				<!-- ================================================= -->\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<!-- 탭 끝 -->\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- ================================================= -->\r\n");
      out.write("		<!-- 본문1 끝 -->\r\n");
      out.write("		<!-- ================================================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("	<!-- MAIN-CONTENT 끝 -->\r\n");
      out.write("	<!-- ================================================= -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/tui-date-picker.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(\"#pageHeaderSpan\", parent.document).html(\"강의게시판\");\r\n");
      out.write("$(\"#pageHeaderSpan\", parent.document).attr(\"murl\",\"");
      out.print(request.getContextPath());
      out.write("/prof/lec/main.do?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function f_total(){\r\n");
      out.write("	\r\n");
      out.write("	window.parent.document.getElementById('total').innerHTML = \"점수가 없슈\";\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function f_test(){ \r\n");
      out.write("	alert('박건영의 점수가 저장됐습니다.');\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var datepicker = new tui.DatePicker('#datepicker-div', {\r\n");
      out.write("    date: new Date(),\r\n");
      out.write("    input: {\r\n");
      out.write("        element: '#datepicker-input',\r\n");
      out.write("        format: 'yyyy-MM-dd'\r\n");
      out.write("    },\r\n");
      out.write("    language:'ko'\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//이 아래로 함수쓰면됨.\r\n");
      out.write("datepicker.setNull();\r\n");
      out.write("// datepicker.open();\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("function f_regist(e){\r\n");
      out.write("	var date = datepicker.getDate(); //Thu Oct 13 2022 22:01:13 GMT+0900 (한국 표준시) \r\n");
      out.write("	var v_date = f_transFormatToDate(date); // 2022-10-13\r\n");
      out.write("	\r\n");
      out.write("// // 	console.log(e.target);\r\n");
      out.write("	console.log(date);\r\n");
      out.write("	console.log(v_date);\r\n");
      out.write("	\r\n");
      out.write("	alert('콘솔로그에는 날짜가 있다');\r\n");
      out.write("	\r\n");
      out.write("	//셀렉트칸, 날짜, 강의실 => DB로 insert\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function f_modify(e){\r\n");
      out.write("	console.log(e.target);\r\n");
      out.write("	var dataDate = e.target.getAttribute(\"data-date\");\r\n");
      out.write("	var dataClassroom = e.target.getAttribute(\"data-room\");\r\n");
      out.write("	\r\n");
      out.write("	var dataDivision = e.target.getAttribute(\"data-division\");\r\n");
      out.write("	\r\n");
      out.write("	alert(dataDivision);\r\n");
      out.write("	var v_date = $('td[data-date='+dataDate+']').text(); //날짜\r\n");
      out.write("	var v_Classroom = $('td[data-room='+dataClassroom+']').text(); //강의실\r\n");
      out.write("	var v_division  = $('td[data-division='+dataDivision+']').text(); \r\n");
      out.write("	alert(v_division);\r\n");
      out.write("	\r\n");
      out.write("	datepicker.open();\r\n");
      out.write("	datepicker.setDate(new Date(v_date));\r\n");
      out.write("	\r\n");
      out.write("	document.querySelector('#classroom').value = v_Classroom;\r\n");
      out.write("	\r\n");
      out.write("	var examDivVal = \"\";\r\n");
      out.write("	if (v_division == \"중간고사\") {\r\n");
      out.write("		examDivVal = 'mid';\r\n");
      out.write("	}else if (v_division == \"기말고사\"){\r\n");
      out.write("		\r\n");
      out.write("		examDivVal = 'fin';\r\n");
      out.write("	}else{\r\n");
      out.write("		examDivVal = 'mini';\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	  $(\"#examDiv\").val(examDivVal).prop(\"selected\",true);\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 공지게시판공지게시판공지게시판공지게시판공지게시판 -->\r\n");
      out.write("<!-- 공지게시판공지게시판공지게시판공지게시판공지게시판 -->\r\n");
      out.write("<!-- 공지게시판공지게시판공지게시판공지게시판공지게시판 -->\r\n");
      out.write("<script type=\"text/x-handlebars-template\"  id=\"notList-pagination-template\" >\r\n");
      out.write("\r\n");
      out.write("<li class=\"paginate_button page-item\">\r\n");
      out.write("	<a href=\"1\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		<i class='fas fa-angle-double-left'></i>\r\n");
      out.write("	</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"paginate_button page-item\">\r\n");
      out.write("	<a href=\"{{#if prev}}{{prevPageNum}}{{else}}{{cri.page}}{{/if}}\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		<i class='fas fa-angle-left'></i>\r\n");
      out.write("	</a>\r\n");
      out.write("</li>\r\n");
      out.write("{{#each pageNum}}\r\n");
      out.write("<li class=\"paginate_button page-item {{notSignActive this}} \">\r\n");
      out.write("	<a href=\"{{this}}\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		{{this}}\r\n");
      out.write("	</a>\r\n");
      out.write("</li>\r\n");
      out.write("{{/each}}\r\n");
      out.write("\r\n");
      out.write("<li class=\"paginate_button page-item \">\r\n");
      out.write("	<a href=\"{{#if next}}{{nextPageNum}}{{else}}{{cri.page}}{{/if}}\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		<i class='fas fa-angle-right'></i>\r\n");
      out.write("	</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"paginate_button page-item\">\r\n");
      out.write("	<a href=\"{{realEndPage}}\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		<i class='fas fa-angle-double-right'></i>\r\n");
      out.write("	</a>\r\n");
      out.write("</li>	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/x-handlebars-template\"  id=\"notice-list-template\" >\r\n");
      out.write("	<h2><i class=\"fas fa-clipboard-list\"></i>&nbsp;&nbsp;공지사항</h2>\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("										<!-- 검색바 시작 -->\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("										<div class=\"input-group mb-3 justify-content-end\">\r\n");
      out.write("											<select class=\"form-control col-md-2\" name=\"searchType\"\r\n");
      out.write("												id=\"notSelsearchType\">\r\n");
      out.write("													<option value=\"\">검색옵션</option>\r\n");
      out.write("												 {{#if (eq pageMaker.cri.searchType 't')}}\r\n");
      out.write("                    							<option value=\"t\" selected>글제목</option>\r\n");
      out.write("         										{{else}}\r\n");
      out.write("         										<option value=\"t\" >글제목</option>\r\n");
      out.write("        											 {{/if}}\r\n");
      out.write("         										{{#if (eq pageMaker.cri.searchType 'c')}}\r\n");
      out.write("        										 <option value=\"c\" selected>글내용</option>\r\n");
      out.write("         										{{else}}\r\n");
      out.write("         										<option value=\"c\" >글내용</option>\r\n");
      out.write("         										{{/if}}\r\n");
      out.write("								\r\n");
      out.write("											</select>\r\n");
      out.write("											<!-- keyword -->\r\n");
      out.write("											<input class=\"form-control col-md-3\" type=\"text\" name=\"keyword\" id=\"notSelKeyword\"\r\n");
      out.write("												placeholder=\"검색어를 입력하세요.\" value=\"{{pageMaker.cri.keyword }}\" /> <span\r\n");
      out.write("												class=\"input-group-append\">\r\n");
      out.write("												<button class=\"btn btn-primary btn-sm\" type=\"button\"\r\n");
      out.write("													id=\"searchBtn\" onclick=\"notList_go(1);\">\r\n");
      out.write("													<i class=\"fa fa-fw fa-search\"></i>\r\n");
      out.write("												</button>\r\n");
      out.write("											</span>\r\n");
      out.write("										</div>\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("										<!-- 검색바 끝 -->\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("					\r\n");
      out.write("										<table class=\"table table-hover\">\r\n");
      out.write("											<thead>\r\n");
      out.write("												<tr style=\"background-color:rgba(102,178,255,0.2)\">\r\n");
      out.write("													<th scope=\"col\" style=\"width:470px;\">제목</th>\r\n");
      out.write("													<th scope=\"col\">날짜</th>\r\n");
      out.write("													<th scope=\"col\">조회수</th>\r\n");
      out.write("											</thead>\r\n");
      out.write("											<tbody>\r\n");
      out.write("											{{#each noticeList}}\r\n");
      out.write("													<tr style=\"cursor: pointer;\"onclick=\"OpenWindow('");
      out.print(request.getContextPath());
      out.write("/prof/lec/notice/detail?from=list&lecCd={{lecCd }}&lecNoticeNo={{lecNoticeNo }}','상세보기',600,600);\">\r\n");
      out.write("														<td style=text-align:left;\"> {{cutLongText title}} </td>\r\n");
      out.write("														<td>{{prettifyDate cdate}}</td>\r\n");
      out.write("														<td>{{viewCnt}}</td>\r\n");
      out.write("													</tr>\r\n");
      out.write(" 											{{/each}}\r\n");
      out.write("\r\n");
      out.write("											</tbody>\r\n");
      out.write("										</table>\r\n");
      out.write("<div class=\"row justify-content-end mt-2 mr-2\">\r\n");
      out.write("<button class=\"btn btn-outline-primary\" type=\"button\"onclick=\"OpenWindow('");
      out.print(request.getContextPath());
      out.write("/prof/lec/notice/registForm?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','강의 공지사항 작성');\">작성하기</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("	\r\n");
      out.write("	$('#noticeCardFooter').on('click','li a',function(e){\r\n");
      out.write("		notPage = $(this).attr(\"href\");\r\n");
      out.write("		\r\n");
      out.write("		notList_go(notPage);\r\n");
      out.write("		return false;\r\n");
      out.write("	});\r\n");
      out.write("	getNoticeList('");
      out.print(request.getContextPath());
      out.write("/prof/lec/notice/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&notPage=',notPage);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("var notPage=1;\r\n");
      out.write("function getNoticeList(paramURL,paramPage){\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		\r\n");
      out.write("		method:\"get\",\r\n");
      out.write("		url:paramURL+paramPage,\r\n");
      out.write("		dataType:\"json\",\r\n");
      out.write("		success:(data)=>{ \r\n");
      out.write("			console.log(\"공지 아작스 값\",data);\r\n");
      out.write("			console.log(\"공지 url\",paramURL+paramPage);\r\n");
      out.write("\r\n");
      out.write("			printData(data,$('#noticeCardBody'),$('#notice-list-template'));\r\n");
      out.write("			printPagination(data.pageMaker,$('#noticeCardFooter'),$('#notList-pagination-template'));\r\n");
      out.write("			\r\n");
      out.write("		},\r\n");
      out.write("		error:(request,status,error)=>{\r\n");
      out.write("			alert(\"getAppliedListfn\"+\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function notList_go(page){\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	var jobForm=$('#notjobForm');\r\n");
      out.write("	$('#notPage').val(page);\r\n");
      out.write("	$('#notSearchType').val($('#notSelsearchType').val());\r\n");
      out.write("	$('#notKeyword').val($('#notSelKeyword').val());\r\n");
      out.write("	\r\n");
      out.write("	var searchType = $('#notSelsearchType').val();\r\n");
      out.write("	var keyword = $('#notSelKeyword').val();\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	var paramUrl= \"");
      out.print(request.getContextPath());
      out.write("/prof/lec/notice/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&notPage=\";\r\n");
      out.write("	paramUrl += page;\r\n");
      out.write("	paramUrl += \"&searchType=\";\r\n");
      out.write("	paramUrl += searchType;\r\n");
      out.write("	paramUrl += \"&keyword=\";\r\n");
      out.write("	paramUrl += keyword;\r\n");
      out.write("	\r\n");
      out.write("	console.log(paramUrl);\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		method:\"get\",\r\n");
      out.write("		url:paramUrl,\r\n");
      out.write("		dataType:\"json\",\r\n");
      out.write("		success:(data)=>{\r\n");
      out.write("			printData(data,$('#noticeCardBody'),$('#notice-list-template'));\r\n");
      out.write("			printPagination(data.pageMaker,$('#noticeCardFooter'),$('#notList-pagination-template'));\r\n");
      out.write("		},\r\n");
      out.write("		error:(request,status,error)=>{\r\n");
      out.write("			alert(\"getAppliedListfn\"+\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 공지끝끝끝공지끝끝끝공지끝끝끝공지끝끝끝공지끝끝끝 -->\r\n");
      out.write("<!-- 공지끝끝끝공지끝끝끝공지끝끝끝공지끝끝끝공지끝끝끝 -->\r\n");
      out.write("<!-- 공지끝끝끝공지끝끝끝공지끝끝끝공지끝끝끝공지끝끝끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 질문게시판질문게시판질문게시판질문게시판질문게시판 -->\r\n");
      out.write("<!-- 질문게시판질문게시판질문게시판질문게시판질문게시판 -->\r\n");
      out.write("<!-- 질문게시판질문게시판질문게시판질문게시판질문게시판 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("<script type=\"text/x-handlebars-template\"  id=\"qnaList-pagination-template\" >\r\n");
      out.write("\r\n");
      out.write("<li class=\"paginate_button page-item\">\r\n");
      out.write("	<a href=\"1\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		<i class='fas fa-angle-double-left'></i>\r\n");
      out.write("	</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"paginate_button page-item\">\r\n");
      out.write("	<a href=\"{{#if prev}}{{prevPageNum}}{{else}}{{cri.page}}{{/if}}\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		<i class='fas fa-angle-left'></i>\r\n");
      out.write("	</a>\r\n");
      out.write("</li>\r\n");
      out.write("{{#each pageNum}}\r\n");
      out.write("<li class=\"paginate_button page-item {{qnaSignActive this}} \">\r\n");
      out.write("	<a href=\"{{this}}\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		{{this}}\r\n");
      out.write("	</a>\r\n");
      out.write("</li>\r\n");
      out.write("{{/each}}\r\n");
      out.write("\r\n");
      out.write("<li class=\"paginate_button page-item \">\r\n");
      out.write("	<a href=\"{{#if next}}{{nextPageNum}}{{else}}{{cri.page}}{{/if}}\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		<i class='fas fa-angle-right'></i>\r\n");
      out.write("	</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"paginate_button page-item\">\r\n");
      out.write("	<a href=\"{{realEndPage}}\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		<i class='fas fa-angle-double-right'></i>\r\n");
      out.write("	</a>\r\n");
      out.write("</li>	\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/x-handlebars-template\"  id=\"qna-list-template\" >\r\n");
      out.write("<h2><i class=\"fas fa-clipboard-list\"></i>&nbsp;&nbsp;질문게시판</h2>\r\n");
      out.write("									<!-- ================================================= -->\r\n");
      out.write("									<!-- 검색바 시작 -->\r\n");
      out.write("									<!-- ================================================= -->\r\n");
      out.write("									<div class=\"input-group mb-3 justify-content-end\">\r\n");
      out.write("										<select class=\"form-control col-md-2\" name=\"searchType\"\r\n");
      out.write("											id=\"qnaSelsearchType\">\r\n");
      out.write("												<option value=\"\">검색옵션</option>\r\n");
      out.write("											 {{#if (eq pageMaker.cri.searchType 't')}}\r\n");
      out.write("                							<option value=\"t\" selected>글제목</option>\r\n");
      out.write("     										{{else}}\r\n");
      out.write("     										<option value=\"t\" >글제목</option>\r\n");
      out.write("    											 {{/if}}\r\n");
      out.write("     										{{#if (eq pageMaker.cri.searchType 'c')}}\r\n");
      out.write("    										 <option value=\"c\" selected>글내용</option>\r\n");
      out.write("     										{{else}}\r\n");
      out.write("     										<option value=\"c\" >글내용</option>\r\n");
      out.write("     										{{/if}}\r\n");
      out.write("							\r\n");
      out.write("										</select>\r\n");
      out.write("										<!-- keyword -->\r\n");
      out.write("										<input class=\"form-control col-md-3\" type=\"text\" name=\"keyword\" id=\"qnaSelKeyword\"\r\n");
      out.write("											placeholder=\"검색어를 입력하세요.\" value=\"{{pageMaker.cri.keyword }}\" /> <span\r\n");
      out.write("											class=\"input-group-append\">\r\n");
      out.write("											<button class=\"btn btn-primary btn-sm\" type=\"button\"\r\n");
      out.write("												id=\"searchBtn\" onclick=\"qnaList_go(1);\">\r\n");
      out.write("												<i class=\"fa fa-fw fa-search\"></i>\r\n");
      out.write("											</button>\r\n");
      out.write("										</span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- ================================================= -->\r\n");
      out.write("									<!-- 검색바 끝 -->\r\n");
      out.write("									<!-- ================================================= -->\r\n");
      out.write("				\r\n");
      out.write("									<table class=\"table table-hover\">\r\n");
      out.write("										<thead>\r\n");
      out.write("											<tr style=\"background-color:rgba(102,178,255,0.2)\">\r\n");
      out.write("												<th scope=\"col\" style=\"width:470px;\">제목</th>\r\n");
      out.write("												<th scope=\"col\">작성자</th>\r\n");
      out.write("												<th scope=\"col\">작성일자</th>\r\n");
      out.write("										</thead>\r\n");
      out.write("										<tbody>\r\n");
      out.write("										{{#each lecQnaList}}\r\n");
      out.write("												<tr style=\"cursor: pointer;\"onclick=\"OpenWindow('");
      out.print(request.getContextPath());
      out.write("/prof/lec/qna/detail?lecCd={{lecCd }}&lecqBno={{lecqBno}}','질문상세보기',800,600);\">\r\n");
      out.write("													<td style=\"text-overflow: ellipsis; text-align: left;\">  {{#if response}} <span class=\"text-success\">[답변완료]</span>&nbsp; {{else}}<span class=\"text-warning\">[답변대기중]</span>&nbsp;{{/if}}  {{cutLongText title}} </td>\r\n");
      out.write("													<td>{{stuName}}</td>\r\n");
      out.write("													<td>{{prettifyDate cdate}}</td>\r\n");
      out.write("												</tr>\r\n");
      out.write("											{{/each}}\r\n");
      out.write("\r\n");
      out.write("										</tbody>\r\n");
      out.write("									</table>\r\n");
      out.write("<div class=\"row justify-content-end mt-2 mr-2\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("var qnaPage=1;\r\n");
      out.write("function getqnaList(paramURL,paramPage){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		method:\"get\",\r\n");
      out.write("		url:paramURL+paramPage,\r\n");
      out.write("		dataType:\"json\",\r\n");
      out.write("		success:(data)=>{\r\n");
      out.write("			console.log(\"질문 아작스 값\",data);\r\n");
      out.write("			console.log(\"질문URL\",paramURL+paramPage);\r\n");
      out.write("			printData(data,$('#qnaCardBody'),$('#qna-list-template'));\r\n");
      out.write("			printPagination(data.pageMaker,$('#qnaCardFooter'),$('#qnaList-pagination-template'));\r\n");
      out.write("			\r\n");
      out.write("		},\r\n");
      out.write("		error:(request,status,error)=>{\r\n");
      out.write("			alert(\"getAppliedListfn\"+\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("function qnaList_go(page){\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	var jobForm=$('#qnajobForm');\r\n");
      out.write("	$('#qnaPage').val(page);\r\n");
      out.write("	$('#qnaSearchType').val($('#qnaSelsearchType').val());\r\n");
      out.write("	$('#qnaKeyword').val($('#qnaSelKeyword').val());\r\n");
      out.write("	\r\n");
      out.write("	var searchType = $('#qnaSelsearchType').val();\r\n");
      out.write("	var keyword = $('#qnaSelKeyword').val();\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	var paramUrl= \"");
      out.print(request.getContextPath());
      out.write("/prof/lec/qna/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&qnaPage=\";\r\n");
      out.write("	paramUrl += page;\r\n");
      out.write("	paramUrl += \"&searchType=\";\r\n");
      out.write("	paramUrl += searchType;\r\n");
      out.write("	paramUrl += \"&keyword=\";\r\n");
      out.write("	paramUrl += keyword;\r\n");
      out.write("	\r\n");
      out.write("	console.log(paramUrl);\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		method:\"get\",\r\n");
      out.write("		url:paramUrl,\r\n");
      out.write("		dataType:\"json\",\r\n");
      out.write("		success:(data)=>{\r\n");
      out.write("			printData(data,$('#qnaCardBody'),$('#qna-list-template'));\r\n");
      out.write("			printPagination(data.pageMaker,$('#qnaCardFooter'),$('#qnaList-pagination-template'));\r\n");
      out.write("		},\r\n");
      out.write("		error:(request,status,error)=>{\r\n");
      out.write("			alert(\"getAppliedListfn\"+\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("	\r\n");
      out.write("	$('#qnaCardFooter').on('click','li a',function(e){\r\n");
      out.write("		qnaPage = $(this).attr(\"href\");\r\n");
      out.write("		\r\n");
      out.write("		qnaList_go(qnaPage);\r\n");
      out.write("		return false;\r\n");
      out.write("	});\r\n");
      out.write("	getqnaList('");
      out.print(request.getContextPath());
      out.write("/prof/lec/qna/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&qnaPage=',qnaPage);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 질문끝끝끝질문끝끝끝질문끝끝끝질문끝끝끝질문끝끝끝 -->\r\n");
      out.write("<!-- 질문끝끝끝질문끝끝끝질문끝끝끝질문끝끝끝질문끝끝끝 -->\r\n");
      out.write("<!-- 질문끝끝끝질문끝끝끝질문끝끝끝질문끝끝끝질문끝끝끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 과제게시판과제게시판과제게시판과제게시판과제게시판 -->\r\n");
      out.write("<!-- 과제게시판과제게시판과제게시판과제게시판과제게시판 -->\r\n");
      out.write("<!-- 과제게시판과제게시판과제게시판과제게시판과제게시판 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/x-handlebars-template\"  id=\"assList-pagination-template\" >\r\n");
      out.write("\r\n");
      out.write("<li class=\"paginate_button page-item\">\r\n");
      out.write("	<a href=\"1\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		<i class='fas fa-angle-double-left'></i>\r\n");
      out.write("	</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"paginate_button page-item\">\r\n");
      out.write("	<a href=\"{{#if prev}}{{prevPageNum}}{{else}}{{cri.page}}{{/if}}\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		<i class='fas fa-angle-left'></i>\r\n");
      out.write("	</a>\r\n");
      out.write("</li>\r\n");
      out.write("{{#each pageNum}}\r\n");
      out.write("<li class=\"paginate_button page-item {{assSignActive this}} \">\r\n");
      out.write("	<a href=\"{{this}}\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		{{this}}\r\n");
      out.write("	</a>\r\n");
      out.write("</li>\r\n");
      out.write("{{/each}}\r\n");
      out.write("\r\n");
      out.write("<li class=\"paginate_button page-item \">\r\n");
      out.write("	<a href=\"{{#if next}}{{nextPageNum}}{{else}}{{cri.page}}{{/if}}\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		<i class='fas fa-angle-right'></i>\r\n");
      out.write("	</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"paginate_button page-item\">\r\n");
      out.write("	<a href=\"{{realEndPage}}\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">\r\n");
      out.write("		<i class='fas fa-angle-double-right'></i>\r\n");
      out.write("	</a>\r\n");
      out.write("</li>	\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/x-handlebars-template\"  id=\"assignment-list-template\" >\r\n");
      out.write("	<h2><i class=\"fas fa-clipboard-list\"></i>&nbsp;&nbsp;과제관리</h2>\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("										<!-- 검색바 시작 -->\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("										<div class=\"input-group mb-3 justify-content-end\">\r\n");
      out.write("											<select class=\"form-control col-md-2\" name=\"searchType\"\r\n");
      out.write("												id=\"assSelsearchType\">\r\n");
      out.write("													<option value=\"\">검색옵션</option>\r\n");
      out.write("												 {{#if (eq pageMaker.cri.searchType 't')}}\r\n");
      out.write("                    							<option value=\"t\" selected>글제목</option>\r\n");
      out.write("         										{{else}}\r\n");
      out.write("         										<option value=\"t\" >글제목</option>\r\n");
      out.write("        											 {{/if}}\r\n");
      out.write("         										{{#if (eq pageMaker.cri.searchType 'c')}}\r\n");
      out.write("        										 <option value=\"c\" selected>글내용</option>\r\n");
      out.write("         										{{else}}\r\n");
      out.write("         										<option value=\"c\" >글내용</option>\r\n");
      out.write("         										{{/if}}\r\n");
      out.write("								\r\n");
      out.write("											</select>\r\n");
      out.write("											<!-- keyword -->\r\n");
      out.write("											<input class=\"form-control col-md-3\" type=\"text\" name=\"keyword\" id=\"assSelKeyword\"\r\n");
      out.write("												placeholder=\"검색어를 입력하세요.\" value=\"{{pageMaker.cri.keyword }}\" /> <span\r\n");
      out.write("												class=\"input-group-append\">\r\n");
      out.write("												<button class=\"btn btn-primary btn-sm\" type=\"button\"\r\n");
      out.write("													id=\"searchBtn\" onclick=\"assList_go(1);\">\r\n");
      out.write("													<i class=\"fa fa-fw fa-search\"></i>\r\n");
      out.write("												</button>\r\n");
      out.write("											</span>\r\n");
      out.write("										</div>\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("										<!-- 검색바 끝 -->\r\n");
      out.write("										<!-- ================================================= -->\r\n");
      out.write("					\r\n");
      out.write("										<table class=\"table table-hover\">\r\n");
      out.write("											<thead>\r\n");
      out.write("												<tr style=\"background-color:rgba(102,178,255,0.2)\">\r\n");
      out.write("													<th scope=\"col\">제목</th>\r\n");
      out.write("													<th scope=\"col\">마감일</th>\r\n");
      out.write("											</thead>\r\n");
      out.write("											<tbody>\r\n");
      out.write("											{{#each assignmentList}}\r\n");
      out.write("													<tr style=\"cursor: pointer;\"onclick=\"OpenWindow('");
      out.print(request.getContextPath());
      out.write("/prof/lec/assignment/detail?lecCd={{lecCd }}&assBno={{assBno }}','과제 상세보기',800,400);\">\r\n");
      out.write("														<td style=\"text-align: left;\"> {{cutLongText title}} </td>\r\n");
      out.write("														<td>{{prettifyDate dueDate}}</td>\r\n");
      out.write("													</tr>\r\n");
      out.write(" 											{{/each}}\r\n");
      out.write("\r\n");
      out.write("											</tbody>\r\n");
      out.write("										</table>\r\n");
      out.write("<div class=\"row justify-content-end mt-2 mr-2\">\r\n");
      out.write("<button class=\"btn btn-outline-primary\" type=\"button\"onclick=\"OpenWindow('");
      out.print(request.getContextPath());
      out.write("/prof/lec/assignment/registForm?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','과제 등록하기',1660,630);\">과제등록</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("	\r\n");
      out.write("	$('#assignmentCardFooter').on('click','li a',function(e){\r\n");
      out.write("		assPage = $(this).attr(\"href\");\r\n");
      out.write("		\r\n");
      out.write("		assList_go(assPage);\r\n");
      out.write("		return false;\r\n");
      out.write("	});\r\n");
      out.write("	getAssignmentList('");
      out.print(request.getContextPath());
      out.write("/prof/lec/assignment/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&assPage=',assPage);\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var assPage=1;\r\n");
      out.write("function getAssignmentList(paramURL,paramPage){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		\r\n");
      out.write("		method:\"get\",\r\n");
      out.write("		url:paramURL+paramPage,\r\n");
      out.write("		dataType:\"json\",\r\n");
      out.write("		success:(data)=>{\r\n");
      out.write("			console.log(\"과제 아작스 값\",data);\r\n");
      out.write("			\r\n");
      out.write("			printData(data,$('#assignmentCardBody'),$('#assignment-list-template'));\r\n");
      out.write("			printPagination(data.pageMaker,$('#assignmentCardFooter'),$('#assList-pagination-template'));\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		},\r\n");
      out.write("		error:(request,status,error)=>{\r\n");
      out.write("			alert(\"getAppliedListfn\"+\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function printData(data,target,templateObject){\r\n");
      out.write("	var template=Handlebars.compile(templateObject.html());\r\n");
      out.write("	var html = template(data);	\r\n");
      out.write("	target.html(html);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function printPagination(pageMaker,target,templateObject){\r\n");
      out.write("	var pageNumArray = new Array(pageMaker.endPage-pageMaker.startPage+1);\r\n");
      out.write("	for(var i=0;i<pageMaker.endPage-pageMaker.startPage+1;i++){\r\n");
      out.write("		pageNumArray[i]=pageMaker.startPage+i;\r\n");
      out.write("	}	\r\n");
      out.write("	pageMaker.pageNum=pageNumArray; \r\n");
      out.write("	\r\n");
      out.write("	if (pageMaker.startPage == 1) {\r\n");
      out.write("		pageMaker.prev = false;\r\n");
      out.write("		pageMaker.prevPageNum=pageMaker.startPage-1;\r\n");
      out.write("	}else{\r\n");
      out.write("		pageMaker.prev = true;\r\n");
      out.write("		pageMaker.prevPageNum=pageMaker.cri.page;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if (pageMaker.endPage >= pageMaker.realEndPage) {\r\n");
      out.write("		pageMaker.next = false;\r\n");
      out.write("		\r\n");
      out.write("	}else{\r\n");
      out.write("		pageMaker.next = true;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	pageMaker.nextPageNum=pageMaker.cri.page+1;\r\n");
      out.write("	\r\n");
      out.write("	var template=Handlebars.compile(templateObject.html());	\r\n");
      out.write("	var html = template(pageMaker);	\r\n");
      out.write("	target.html(html);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("Handlebars.registerHelper({\r\n");
      out.write("	\"assSignActive\":function(pageNum){\r\n");
      out.write("		if(pageNum == assPage) return 'active';\r\n");
      out.write("	},\r\n");
      out.write("	\"notSignActive\":function(pageNum){\r\n");
      out.write("		if(pageNum == notPage) return 'active';\r\n");
      out.write("	},\r\n");
      out.write("	\"qnaSignActive\":function(pageNum){\r\n");
      out.write("		if(pageNum == qnaPage) return 'active';\r\n");
      out.write("	},\r\n");
      out.write("	\"prettifyDate\":function(timeValue){ //Handlbars에 날짜출력함수 등록\r\n");
      out.write("		var dateObj=new Date(timeValue);\r\n");
      out.write("		var year=dateObj.getFullYear();\r\n");
      out.write("		var month=dateObj.getMonth()+1;\r\n");
      out.write("		var date=dateObj.getDate();\r\n");
      out.write("		return year+\"/\"+month+\"/\"+date;\r\n");
      out.write("	},\r\n");
      out.write("	\"cutLongText\":function(text){\r\n");
      out.write("		if (text.length>30) {\r\n");
      out.write("			return text.substr(0,30) + \"...\";\r\n");
      out.write("		}\r\n");
      out.write("		return text;\r\n");
      out.write("	}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("Handlebars.registerHelper('eq', (a, b) => a == b);\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function assList_go(page){\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	var jobForm=$('#assjobForm');\r\n");
      out.write("	$('#assPage').val(page);\r\n");
      out.write("	$('#assSearchType').val($('#assSelsearchType').val());\r\n");
      out.write("	$('#assKeyword').val($('#assSelKeyword').val());\r\n");
      out.write("	\r\n");
      out.write("	var searchType = $('#assSelsearchType').val();\r\n");
      out.write("	var keyword = $('#assSelKeyword').val();\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	var paramUrl= \"");
      out.print(request.getContextPath());
      out.write("/prof/lec/assignment/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&assPage=\";\r\n");
      out.write("	paramUrl += page;\r\n");
      out.write("	paramUrl += \"&searchType=\";\r\n");
      out.write("	paramUrl += searchType;\r\n");
      out.write("	paramUrl += \"&keyword=\";\r\n");
      out.write("	paramUrl += keyword;\r\n");
      out.write("	\r\n");
      out.write("	console.log(paramUrl);\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		method:\"get\",\r\n");
      out.write("		url:paramUrl,\r\n");
      out.write("		dataType:\"json\",\r\n");
      out.write("		success:(data)=>{\r\n");
      out.write("			printData(data,$('#assignmentCardBody'),$('#assignment-list-template'));\r\n");
      out.write("			printPagination(data.pageMaker,$('#assignmentCardFooter'),$('#assList-pagination-template'));\r\n");
      out.write("		},\r\n");
      out.write("		error:(request,status,error)=>{\r\n");
      out.write("			alert(\"getAppliedListfn\"+\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 과제끝끝끝과제끝끝끝과제끝끝끝과제끝끝끝과제끝끝끝 -->\r\n");
      out.write("<!-- 과제끝끝끝과제끝끝끝과제끝끝끝과제끝끝끝과제끝끝끝 -->\r\n");
      out.write("<!-- 과제끝끝끝과제끝끝끝과제끝끝끝과제끝끝끝과제끝끝끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var examPage = 1;\r\n");
      out.write("$(function(){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		method:'get',\r\n");
      out.write("		url:'");
      out.print(request.getContextPath());
      out.write("/prof/lec/exam/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&examPage='+examPage,\r\n");
      out.write("		dataType:\"json\",\r\n");
      out.write("		success:(data)=>{\r\n");
      out.write("			let examList = data.examList;\r\n");
      out.write("			let pageMaker = data.pageMaker;\r\n");
      out.write("			let cri = data.pageMaker.cri;\r\n");
      out.write("			\r\n");
      out.write("			var v_TbodyStr = \"\";\r\n");
      out.write("			var v_pageStr = \"\";\r\n");
      out.write("			var examTbody = document.querySelector(\"#examTbody\");\r\n");
      out.write("			var examPage = document.querySelector(\"#examPagenation\");\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			for (var i = 0; i < examList.length; i++) {\r\n");
      out.write("				v_TbodyStr += `<tr>`;\r\n");
      out.write("				v_TbodyStr += `<td data-division=\"v_div`+i+`\">${data.examList[i].examDivName}</td>`;\r\n");
      out.write("				v_TbodyStr += `<td data-date=\"v_date`+i+`\">${data.examList[i].examDate}</td>`;\r\n");
      out.write("				v_TbodyStr += `<td data-room=\"v_classroom`+i+`\">${data.examList[i].examCr}</td>`;\r\n");
      out.write("				v_TbodyStr += `<td>\r\n");
      out.write("					<button class=\"btn btn-outline-primary btn-xs m-1 mb-2\" type=\"button\" data-division=\"v_div`+i+`\" data-date=\"v_date`+i+`\" data-room=\"v_classroom`+i+`\"\r\n");
      out.write("					onclick=\"f_modify(event)\">수정</button></td>`;\r\n");
      out.write("				v_TbodyStr += `	<td>\r\n");
      out.write("					<button class=\"btn btn-outline-danger btn-xs m-1 mb-2\" type=\"button\" onclick=\"javascript:alert('삭제...');\">삭제</button>\r\n");
      out.write("					</td>`;\r\n");
      out.write("				v_TbodyStr += `</tr>`;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("	         v_pageStr += `<li class=\"page-item\">`;\r\n");
      out.write("	         v_pageStr += `<a class=\"page-link\" href=\"javascript:examList_go(1);\">`;\r\n");
      out.write("	         v_pageStr += `<i class=\"fas fa-angle-double-left\"></i></a></li>`;\r\n");
      out.write("	         \r\n");
      out.write("	         v_pageStr += `<li class=\"page-item\">`;\r\n");
      out.write("	         v_pageStr += `<a class=\"page-link\" href=\"javascript:examList_go('${pageMaker.prev ? pageMaker.startPage-1 : cri.page}');\">`;\r\n");
      out.write("	         v_pageStr += `<i class=\"fas fa-angle-left\"></i></a></li>`;\r\n");
      out.write("	         \r\n");
      out.write("	            \r\n");
      out.write("	               \r\n");
      out.write("	            for (var i = pageMaker.startPage; i <= pageMaker.endPage; i++) {\r\n");
      out.write("	               v_pageStr += `<li class=\"page-item ${cri.page == i?'active':''}\">`;\r\n");
      out.write("	               v_pageStr += `<a class=\"page-link\" href=\"javascript:examList_go('`+i+`');\" >`+i+`</a></li>`;\r\n");
      out.write("	            }\r\n");
      out.write("	            \r\n");
      out.write("	            v_pageStr += `<li class=\"page-item\">`;\r\n");
      out.write("	            v_pageStr += `<a class=\"page-link\" href=\"javascript:examList_go('${pageMaker.next ? pageMaker.endPage+1 :cri.page}');\">`;\r\n");
      out.write("	            v_pageStr += `<i class=\"fas fa-angle-right\" ></i></a></li>`;\r\n");
      out.write("	            v_pageStr += `<li class=\"page-item\">`;\r\n");
      out.write("	            v_pageStr += `<a class=\"page-link\" href=\"javascript:examList_go('${pageMaker.realEndPage}');\">`;\r\n");
      out.write("	            v_pageStr += ``;\r\n");
      out.write("	            \r\n");
      out.write("	            v_pageStr += `<i class=\"fas fa-angle-double-right\"></i></a></li>`;\r\n");
      out.write("			\r\n");
      out.write("			examTbody.innerHTML = v_TbodyStr;\r\n");
      out.write("			examPage.innerHTML = v_pageStr;\r\n");
      out.write("		},\r\n");
      out.write("		error:(request,status,error)=>{\r\n");
      out.write("			alert(\"getAppliedListfn\"+\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function examList_go(page){\r\n");
      out.write("	\r\n");
      out.write("	var paramUrl= \"");
      out.print(request.getContextPath());
      out.write("/prof/lec/exam/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&page=\";\r\n");
      out.write("	paramUrl += page;\r\n");
      out.write("	console.log(paramUrl);\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		method:\"get\",\r\n");
      out.write("		url:paramUrl,\r\n");
      out.write("		dataType:\"json\",\r\n");
      out.write("		success:(data)=>{\r\n");
      out.write("			let examList = data.examList;\r\n");
      out.write("			let pageMaker = data.pageMaker;\r\n");
      out.write("			let cri = data.pageMaker.cri;\r\n");
      out.write("			\r\n");
      out.write("			var v_TbodyStr = \"\";\r\n");
      out.write("			var v_pageStr = \"\";\r\n");
      out.write("			var examTbody = document.querySelector(\"#examTbody\");\r\n");
      out.write("			var examPage = document.querySelector(\"#examPagenation\");\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			for (var i = 0; i < examList.length; i++) {\r\n");
      out.write("				v_TbodyStr += `<tr>`;\r\n");
      out.write("				v_TbodyStr += `<td data-division=\"v_div`+i+`\">${data.examList[i].examDivName}</td>`;\r\n");
      out.write("				v_TbodyStr += `<td data-date=\"v_date`+i+`\">${data.examList[i].examDate}</td>`;\r\n");
      out.write("				v_TbodyStr += `<td data-room=\"v_classroom`+i+`\">${data.examList[i].examCr}</td>`;\r\n");
      out.write("				v_TbodyStr += `<td>\r\n");
      out.write("					<button class=\"btn btn-outline-primary btn-xs m-1 mb-2\" type=\"button\" data-division=\"v_div`+i+`\" data-date=\"v_date`+i+`\" data-room=\"v_classroom`+i+`\"\r\n");
      out.write("					onclick=\"f_modify(event)\">수정</button></td>`;\r\n");
      out.write("				v_TbodyStr += `	<td>\r\n");
      out.write("					<button class=\"btn btn-outline-danger btn-xs m-1 mb-2\" type=\"button\" onclick=\"javascript:alert('삭제...');\">삭제</button>\r\n");
      out.write("					</td>`;\r\n");
      out.write("				v_TbodyStr += `</tr>`;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("	         v_pageStr += `<li class=\"page-item\">`;\r\n");
      out.write("	         v_pageStr += `<a class=\"page-link\" href=\"javascript:examList_go(1);\">`;\r\n");
      out.write("	         v_pageStr += `<i class=\"fas fa-angle-double-left\"></i></a></li>`;\r\n");
      out.write("	         \r\n");
      out.write("	         v_pageStr += `<li class=\"page-item\">`;\r\n");
      out.write("	         v_pageStr += `<a class=\"page-link\" href=\"javascript:examList_go('${pageMaker.prev ? pageMaker.startPage-1 : cri.page}');\">`;\r\n");
      out.write("	         v_pageStr += `<i class=\"fas fa-angle-left\"></i></a></li>`;\r\n");
      out.write("	         \r\n");
      out.write("	            \r\n");
      out.write("	               \r\n");
      out.write("	            for (var i = pageMaker.startPage; i <= pageMaker.endPage; i++) {\r\n");
      out.write("	               v_pageStr += `<li class=\"page-item ${cri.page == i?'active':''}\">`;\r\n");
      out.write("	               v_pageStr += `<a class=\"page-link\" href=\"javascript:examList_go('`+i+`');\" >`+i+`</a></li>`;\r\n");
      out.write("	            }\r\n");
      out.write("	            \r\n");
      out.write("	            v_pageStr += `<li class=\"page-item\">`;\r\n");
      out.write("	            v_pageStr += `<a class=\"page-link\" href=\"javascript:examList_go('${pageMaker.next ? pageMaker.endPage+1 :cri.page}');\">`;\r\n");
      out.write("	            v_pageStr += `<i class=\"fas fa-angle-right\" ></i></a></li>`;\r\n");
      out.write("	            v_pageStr += `<li class=\"page-item\">`;\r\n");
      out.write("	            v_pageStr += `<a class=\"page-link\" href=\"javascript:examList_go('${pageMaker.realEndPage}');\">`;\r\n");
      out.write("	            v_pageStr += ``;\r\n");
      out.write("	            \r\n");
      out.write("	            v_pageStr += `<i class=\"fas fa-angle-double-right\"></i></a></li>`;\r\n");
      out.write("			\r\n");
      out.write("			examTbody.innerHTML = v_TbodyStr;\r\n");
      out.write("			examPage.innerHTML = v_pageStr;\r\n");
      out.write("			\r\n");
      out.write("		},\r\n");
      out.write("		error:(request,status,error)=>{\r\n");
      out.write("			alert(\"getAppliedListfn\"+\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/prof/lec/lecBoardMain.jsp(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("assignmentList");
      // /WEB-INF/views/prof/lec/lecBoardMain.jsp(12,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/prof/lec/lecBoardMain.jsp(12,0) '${assignemtDataMap.assignmentList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${assignemtDataMap.assignmentList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/prof/lec/lecBoardMain.jsp(13,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("assignmentPageMaker");
      // /WEB-INF/views/prof/lec/lecBoardMain.jsp(13,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/prof/lec/lecBoardMain.jsp(13,0) '${assignemtDataMap.assignmentPageMaker }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${assignemtDataMap.assignmentPageMaker }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/prof/lec/lecBoardMain.jsp(14,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("assignmentCri");
      // /WEB-INF/views/prof/lec/lecBoardMain.jsp(14,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/prof/lec/lecBoardMain.jsp(14,0) '${assignmentPageMaker.cri }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${assignmentPageMaker.cri }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/prof/lec/lecBoardMain.jsp(1129,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${from eq 'regist' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<script>\r\n");
          out.write("		window.close();\r\n");
          out.write("		alert(\"등록되었습니다.\");\r\n");
          out.write("		window.opener.location.reload();			\r\n");
          out.write("	</script>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/prof/lec/lecBoardMain.jsp(1136,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${from eq 'remove' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<script>\r\n");
          out.write("		window.close();\r\n");
          out.write("		alert(\"삭제되었습니다.\");\r\n");
          out.write("		window.opener.location.reload();			\r\n");
          out.write("	</script>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
