/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-11-27 02:35:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1662347357502L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("#enterCR{\r\n");
      out.write("\r\n");
      out.write("position:fixed;\r\n");
      out.write("top:200px;\r\n");
      out.write("left:1900px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("\r\n");
      out.write("background-image: linear-gradient( rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.1) ),url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${webPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/loginbackground.jpg\");\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginWindowMain{\r\n");
      out.write("	width:700px;\r\n");
      out.write("	position:absolute;\r\n");
      out.write("	top:25%;\r\n");
      out.write("	right:30%;\r\n");
      out.write("}\r\n");
      out.write("#loginWindow2{\r\n");
      out.write("	width:345px;\r\n");
      out.write("	height:441.5px;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("/* 	opacity: 0.8; */\r\n");
      out.write("}\r\n");
      out.write("#loginWindow{\r\n");
      out.write("	width:345px;\r\n");
      out.write("	height:441.5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <div class=\"splash-container\">\r\n");
      out.write("   	  <div class=\"row\" id=\"loginWindowMain\">\r\n");
      out.write("   	  <div class=\"card\" id=\"loginWindow2\">\r\n");
      out.write("   	   \r\n");
      out.write("   	   \r\n");
      out.write("<!-- 		<div class=\"card-body\"> -->\r\n");
      out.write("				<div id=\"carouselExampleIndicators\" class=\"carousel slide\"\r\n");
      out.write("					data-ride=\"carousel\">\r\n");
      out.write("					<ol class=\"carousel-indicators\">\r\n");
      out.write("						<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\"\r\n");
      out.write("							class=\"active\"></li>\r\n");
      out.write("						<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"\r\n");
      out.write("							class=\"\"></li>\r\n");
      out.write("						<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"\r\n");
      out.write("							class=\"\"></li>\r\n");
      out.write("					</ol>\r\n");
      out.write("					<div class=\"carousel-inner\">\r\n");
      out.write("						<div class=\"carousel-item active\">\r\n");
      out.write("							<img class=\"d-block w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${webPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/pop1.jpg\"\r\n");
      out.write("								alt=\"First slide\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"carousel-item\">\r\n");
      out.write("							<img class=\"d-block w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${webPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/pop2.jpg\"\r\n");
      out.write("								alt=\"Second slide\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"carousel-item\">\r\n");
      out.write("							<img class=\"d-block w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${webPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/pop3.jpg\"\r\n");
      out.write("								alt=\"Third slide\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\"\r\n");
      out.write("						role=\"button\" data-slide=\"prev\"> <span\r\n");
      out.write("						class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("						class=\"sr-only\">Previous</span>\r\n");
      out.write("					</a> <a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\"\r\n");
      out.write("						role=\"button\" data-slide=\"next\"> <span\r\n");
      out.write("						class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("						class=\"sr-only\">Next</span>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("<!-- 			</div> -->\r\n");
      out.write("   	   \r\n");
      out.write("   	   \r\n");
      out.write("   	   \r\n");
      out.write("   	  </div>\r\n");
      out.write("   	  \r\n");
      out.write("      <div class=\"card\" id=\"loginWindow\">\r\n");
      out.write("         <div class=\"card-header text-center\" style=\"padding-bottom:5px\">\r\n");
      out.write("            <img class=\"logo-img\"\r\n");
      out.write("               src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/로고.jpg\" alt=\" logo\"><span\r\n");
      out.write("               class=\"splash-description\"></span>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"card-body\">\r\n");
      out.write("            <form method=\"post\" action = \"login.do\">\r\n");
      out.write("               <div class=\"form-group\">\r\n");
      out.write("                  <input class=\"form-control form-control-lg\" id=\"username\"\r\n");
      out.write("                     type=\"text\" name=\"id\" placeholder=\"아이디\" autocomplete=\"off\">\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"form-group\">\r\n");
      out.write("                  <input class=\"form-control form-control-lg\" id=\"password\"\r\n");
      out.write("                     type=\"password\" name=\"pwd\" placeholder=\"비밀번호\">\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"form-group\">\r\n");
      out.write("               		<div class=\"justify-content-center flex row\">\r\n");
      out.write("	                  <button type=\"button\" class=\"btn btn-outline-dark\" style=\"margin-left:10px;\"  onclick=\"autoInput('staff')\">교직원</button>\r\n");
      out.write("	                  <button type=\"button\" class=\"btn btn-outline-dark\" style=\"margin-left:10px;\"  onclick=\"autoInput('prof')\">교수</button>\r\n");
      out.write("	                  <button type=\"button\" class=\"btn btn-outline-dark\" style=\"margin-left:10px;\" onclick=\"autoInput('stu')\">학생</button>\r\n");
      out.write("               		</div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <button type=\"submit\" class=\"btn btn-primary btn-lg btn-block\">로그인</button>\r\n");
      out.write("            </form>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"card-footer\" >\r\n");
      out.write("         	<div class=\"justify-content-center row\">\r\n");
      out.write("         		<div class=\"col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 row\">\r\n");
      out.write("         		<div class=\"col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("               <button type=\"button\" class=\"btn btn-outline-dark\" onclick=\"OpenWindow('");
      out.print(request.getContextPath());
      out.write("/common/login/resetPwd.do','_blank',450,500);\">\r\n");
      out.write("               <strong>비밀번호 재설정</strong></button>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("               <button type=\"button\" class=\"btn btn-outline-dark\" onclick=\"OpenWindow('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${webPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/common/getCameraLogin','카메라로 인증',1200,800)\"><strong>출입 인증하기</strong></button>\r\n");
      out.write("    	  		</div>\r\n");
      out.write("    	  		</div>\r\n");
      out.write("    	  	</div>\r\n");
      out.write("    	  </div>\r\n");
      out.write("    	  <div>\r\n");
      out.write("    	  \r\n");
      out.write("    	  </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	function autoInput(entity){\r\n");
      out.write("		if(entity=='staff'){\r\n");
      out.write("			var staffId='staff0001';\r\n");
      out.write("			var staffPw='1234';\r\n");
      out.write("			$('#username').val(staffId);\r\n");
      out.write("			$('#password').val(staffPw);\r\n");
      out.write("			\r\n");
      out.write("		}else if(entity=='stu'){\r\n");
      out.write("			var stuId='stu0001';\r\n");
      out.write("			var stuPw='1234';\r\n");
      out.write("			$('#username').val(stuId);\r\n");
      out.write("			$('#password').val(stuPw);\r\n");
      out.write("			\r\n");
      out.write("		}else if(entity=='prof'){\r\n");
      out.write("			var profId='prof0001';\r\n");
      out.write("			var profPw='1234';\r\n");
      out.write("			$('#username').val(profId);\r\n");
      out.write("			$('#password').val(profPw);\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <script src=\"../assets/vendor/jquery/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("   <script src=\"../assets/vendor/bootstrap/js/bootstrap.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   <script async=\"\"\r\n");
      out.write("      src=\"https://www.googletagmanager.com/gtag/js?id=UA-23581568-13\"></script>\r\n");
      out.write("   <script>\r\n");
      out.write("      window.dataLayer = window.dataLayer || [];\r\n");
      out.write("      function gtag() {\r\n");
      out.write("         dataLayer.push(arguments);\r\n");
      out.write("      }\r\n");
      out.write("      gtag('js', new Date());\r\n");
      out.write("\r\n");
      out.write("      gtag('config', 'UA-23581568-13');\r\n");
      out.write("   </script>\r\n");
      out.write("   <script defer=\"\"\r\n");
      out.write("      src=\"https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194\"\r\n");
      out.write("      integrity=\"sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw==\"\r\n");
      out.write("      data-cf-beacon=\"{&quot;rayId&quot;:&quot;758529c84b4534b1&quot;,&quot;token&quot;:&quot;cd0b4b3a733644fc843ef0b185f98241&quot;,&quot;version&quot;:&quot;2022.8.1&quot;,&quot;si&quot;:100}\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
