/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-11-08 01:54:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.stu.lec;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myLectureAssignPdsList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1662347357502L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"pills-regular col-xl-12\">\r\n");
      out.write("\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<!-- 탭LIST 시작 -->\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<ul class=\"nav nav-pills mb-1\" id=\"pills-tab\" role=\"tablist\">\r\n");
      out.write("				<li class=\"menuMove nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					data-url=\"");
      out.print(request.getContextPath() );
      out.write("/mylecture/notice/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("					id=\"Stulenotice-tab\" data-toggle=\"pill\" href=\"#pills-lecnotice\"\r\n");
      out.write("					role=\"tab\" aria-controls=\"home\" aria-selected=\"true\">공지사항</a></li>\r\n");
      out.write("				<li class=\"menuMove nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					data-url=\"");
      out.print(request.getContextPath());
      out.write("/stu/lec/mylecture/assign/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("					id=\"Stulecassignment-tab\" data-toggle=\"pill\" href=\"#pills-lecqna\"\r\n");
      out.write("					role=\"tab\" aria-controls=\"profile\" aria-selected=\"false\">과제게시판</a></li>\r\n");
      out.write("				<li class=\"menuMove nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					data-url=\"");
      out.print(request.getContextPath() );
      out.write("/stu/lec/mylecture/assign/syllabus.do?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("					id=\"Stureviews-tab\" data-toggle=\"pill\" href=\"#pills-lecassignment\"\r\n");
      out.write("					role=\"tab\" aria-controls=\"contact\" aria-selected=\"false\">강의계획서</a></li>\r\n");
      out.write("				<li class=\"menuMove nav-item\"><a class=\"nav-link active show\"\r\n");
      out.write("					data-url=\"");
      out.print(request.getContextPath() );
      out.write("/stu/lec/mylecture/assign/pds/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("					id=\"StuReference-tab\" data-toggle=\"pill\" href=\"#pills-lecmarks\"\r\n");
      out.write("					role=\"tab\" aria-controls=\"contact\" aria-selected=\"false\">자료실</a></li>\r\n");
      out.write("				<li class=\"menuMove nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					data-url=\"");
      out.print(request.getContextPath() );
      out.write("/stu/lec/mylecture/assign/qna/list?lecCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("					id=\"StuQna-tab\" data-toggle=\"pill\" href=\"#pills-lecattend\"\r\n");
      out.write("					role=\"tab\" aria-controls=\"contact\" aria-selected=\"false\">Q&A</a></li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<!-- 탭 LIST 끝 -->\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<!-- 카드 시작 -->\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<!-- 게시판상세 -->\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<!-- MAIN-CONTENT -->\r\n");
      out.write("			<!-- ================================================= -->\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"card-header\">\r\n");
      out.write("					<h1 id=\"header\" class=\"header-title\"\r\n");
      out.write("						style=\"text-align: left; margin-top: 20px; margin-left: 20px; display: inline\">\r\n");
      out.write("						<strong>경영학개론</strong>\r\n");
      out.write("					</h1>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<div class=\"main-content-jsp\">\r\n");
      out.write("						<h4 class=\"card-header\">\r\n");
      out.write("							<i class=\"fas fa-clipboard\"></i>&nbsp;&nbsp;경영학개론\r\n");
      out.write("						</h4>\r\n");
      out.write("						<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("							<table class=\"table table-hover\">\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th style=\"width: 20%\">\r\n");
      out.write("										<div class=\"row justify-content-end mr-2\">\r\n");
      out.write("											<label for=\"inputText\"\r\n");
      out.write("												class=\"col-9 col-lg-9 col-form-label text-right\">과목명</label>\r\n");
      out.write("											<div class=\"col-3 col-lg-3\">\r\n");
      out.write("												<div class=\"input-group-append\">\r\n");
      out.write("													<input type=\"text\" class=\"form-control\">\r\n");
      out.write("													<button type=\"button\" class=\"btn btn-primary\">검색</button>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</table>\r\n");
      out.write("							<div class=\"card\">\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<table class=\"table table-hover\">\r\n");
      out.write("										<thead>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th style=\"width: 15%\">글번호</th>\r\n");
      out.write("												<th style=\"width: 55%\">제목</th>\r\n");
      out.write("												<th style=\"width: 15%\">작성일자</th>\r\n");
      out.write("												<th style=\"width: 15%\">조회수</th>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</thead>\r\n");
      out.write("										<tbody>\r\n");
      out.write("											<tr style=\"font-size: 0.85em;\"\r\n");
      out.write("												onclick=\"pageMove('/ai/stu/lec/mylecture/assign/pds/detail')\">\r\n");
      out.write("												<td>541</td>\r\n");
      out.write("												<td>나만의 노트 정리 또는 암기법 공유합니다.</td>\r\n");
      out.write("												<td>2022-09-28 15:12</td>\r\n");
      out.write("												<td>24</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</tbody>\r\n");
      out.write("									</table>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"row justify-content-end mr-2\">\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-lg btn-primary\"\r\n");
      out.write("									data-toggle=\"popover\" title=\"\"\r\n");
      out.write("									data-content=\"And here's some amazing content. It's very engaging. Right?\"\r\n");
      out.write("									data-original-title=\"Popover title\">글쓰기</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"row justify-content-center\">\r\n");
      out.write("								<nav aria-label=\"Page navigation example\">\r\n");
      out.write("									<ul class=\"pagination\">\r\n");
      out.write("										<li class=\"page-item\"><a class=\"page-link\" href=\"#\"\r\n");
      out.write("											aria-label=\"Previous\"> <span aria-hidden=\"true\">«</span>\r\n");
      out.write("												<span class=\"sr-only\">Previous</span>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li class=\"page-item active\"><a class=\"page-link\"\r\n");
      out.write("											href=\"#\">1</a></li>\r\n");
      out.write("										<li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("										<li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("										<li class=\"page-item\"><a class=\"page-link\" href=\"#\"\r\n");
      out.write("											aria-label=\"Next\"> <span aria-hidden=\"true\">»</span> <span\r\n");
      out.write("												class=\"sr-only\">Next</span>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</nav>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function f_alert(){\r\n");
      out.write("	Swal.fire({\r\n");
      out.write("		  title: 'Are you sure?',\r\n");
      out.write("		  text: \"You won't be able to revert this!\",\r\n");
      out.write("		  icon: 'warning',\r\n");
      out.write("		  showCancelButton: true,\r\n");
      out.write("		  confirmButtonColor: '#5969FF',\r\n");
      out.write("		  cancelButtonColor: '#EF172C',\r\n");
      out.write("		  confirmButtonText: 'Yes, delete it!'\r\n");
      out.write("		}).then((result) => {\r\n");
      out.write("		  if (result.isConfirmed) {\r\n");
      out.write("		    Swal.fire(\r\n");
      out.write("		      'Deleted!',\r\n");
      out.write("		      'Your file has been deleted.',\r\n");
      out.write("		      'success'\r\n");
      out.write("		    )\r\n");
      out.write("		  }\r\n");
      out.write("	});\r\n");
      out.write("		\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	var menus = document.querySelectorAll('.menuMove');\r\n");
      out.write("	for (var i = 0; i < menus.length; i++) {\r\n");
      out.write("		menus[i].addEventListener(\"click\", function() {\r\n");
      out.write("			location.href = event.target.getAttribute('data-url');\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
